import { StyleBibleSchema, type StyleBible, type StyleBibleInput } from "../schemas/style-bible";
import type { StylePresetId } from "../schemas/world-spec";

/**
 * Built-in Style Bibles. "stylized_mystical" is the reference direction:
 * chunky low-poly, big silhouettes, giant mushrooms, desaturated palette, diffuse moonlit light, fog.
 */
const PRESETS: Record<StylePresetId, StyleBibleInput> = {
  stylized_mystical: {
    id: "stylized_mystical",
    name: "Stylized Mystical",
    geometry: "chunky_low_poly",
    palette: {
      primary: "#3e5a45",
      secondary: "#6d7a8c",
      accent: "#7b4f8f",
      ground: "#4a3b2c",
      stone: "#7c7f86",
      wood: "#5c3a2a",
      foliage: "#4a7355",
      foliageAlt: "#6a9a62",
      water: "#4d6f86",
      roof: "#6a5a66",
      wall: "#9a8b7a",
      mushroom: "#7b4f8f",
      mushroomAlt: "#8a3f5f",
      glow: "#b48cff",
      sky: "#6d7d9a",
    },
    tree: { style: "chunky_fantasy", scale: [1.0, 1.8], rotationJitterDeg: 25, canopyLayers: [2, 4], trunkTaper: 0.7, hueJitterDeg: 12 },
    mushroom: { scaleMultiplier: [2, 6], capColors: ["#7b4f8f", "#8a3f5f", "#5f4b8b", "#9a5f8f"], glow: 0.35, spots: true },
    rock: { variation: "high", clusterChance: 0.6, mossChance: 0.55 },
    architecture: { style: "medieval_cottage", roofPitch: 0.9, weathering: 0.7, scaleVariance: 0.25, chimneyChance: 0.6 },
    vegetationDensity: 0.72,
    propDensity: 0.5,
    lighting: {
      ambient: "#5d6b85",
      outdoorAmbient: "#6b7690",
      sunColor: "#cfd6e6",
      brightness: 1.2,
      shadowSoftness: 0.7,
      exposure: -0.1,
      colorCorrection: { saturation: -0.05, contrast: 0.06, tint: "#e2e8ff" },
    },
    fog: { start: 80, end: 640, color: "#7d8aa3", atmosphereDensity: 0.36, haze: 1.6, glare: 0.1 },
    biomeTransition: 0.35,
    scaleRules: { landmarkMultiplier: 3.5, foregroundDetail: 1.0, buildingScale: 1.0 },
    randomness: 0.5,
  },
  fantasy: {
    id: "fantasy",
    name: "Fantasy",
    geometry: "chunky_low_poly",
    palette: {
      primary: "#4f7a4a",
      secondary: "#8fa3c7",
      accent: "#d9a94a",
      ground: "#6b5637",
      stone: "#9a9ba3",
      wood: "#6e4a33",
      foliage: "#4a8a48",
      foliageAlt: "#6fa85a",
      water: "#4f8fb0",
      roof: "#8a4b3f",
      wall: "#d8c9a8",
      mushroom: "#c7503e",
      mushroomAlt: "#e0873c",
      glow: "#ffd27f",
      sky: "#8fb4e6",
    },
    tree: { style: "round", scale: [0.9, 1.6], rotationJitterDeg: 15, canopyLayers: [2, 3], trunkTaper: 0.6, hueJitterDeg: 10 },
    mushroom: { scaleMultiplier: [1, 3], capColors: ["#c7503e", "#e0873c", "#d9a94a"], glow: 0.1, spots: true },
    architecture: { style: "timber_frame", roofPitch: 1.0, weathering: 0.25, scaleVariance: 0.2, chimneyChance: 0.8 },
    vegetationDensity: 0.6,
    propDensity: 0.55,
    lighting: { ambient: "#8797b3", outdoorAmbient: "#9fb0c9", sunColor: "#fff2d6", brightness: 2.2, shadowSoftness: 0.4, exposure: 0.1, colorCorrection: { saturation: 0.1, contrast: 0.05, tint: "#fff7ec" } },
    fog: { start: 200, end: 1200, color: "#b7c8e6", atmosphereDensity: 0.28, haze: 1.0, glare: 0.4 },
  },
  medieval: {
    id: "medieval",
    name: "Medieval",
    geometry: "blocky",
    palette: {
      primary: "#5b6b45",
      secondary: "#7a7466",
      accent: "#a83a2f",
      ground: "#5c4a33",
      stone: "#8a8a86",
      wood: "#5a3d2a",
      foliage: "#4a6a3a",
      foliageAlt: "#5f7f44",
      water: "#4b6c7e",
      roof: "#5c3f33",
      wall: "#c9bfa5",
      mushroom: "#a67c52",
      mushroomAlt: "#8a5f3f",
      glow: "#ffb466",
      sky: "#94a5b8",
    },
    tree: { style: "round", scale: [0.9, 1.5], rotationJitterDeg: 10, canopyLayers: [2, 3], trunkTaper: 0.65, hueJitterDeg: 8 },
    mushroom: { scaleMultiplier: [0.8, 1.5], capColors: ["#a67c52", "#8a5f3f"], glow: 0, spots: false },
    architecture: { style: "stone_hut", roofPitch: 1.1, weathering: 0.45, scaleVariance: 0.2, chimneyChance: 0.7 },
    vegetationDensity: 0.5,
    propDensity: 0.6,
    lighting: { ambient: "#7d8798", outdoorAmbient: "#8e98a9", sunColor: "#f6e9d2", brightness: 1.8, shadowSoftness: 0.5, exposure: 0, colorCorrection: { saturation: -0.05, contrast: 0.1, tint: "#f4efe6" } },
    fog: { start: 150, end: 900, color: "#a7b1bf", atmosphereDensity: 0.32, haze: 1.2, glare: 0.2 },
  },
  cartoon: {
    id: "cartoon",
    name: "Cartoon",
    geometry: "rounded",
    palette: {
      primary: "#5ec46a",
      secondary: "#62b6ff",
      accent: "#ff7b54",
      ground: "#9a6b3f",
      stone: "#aeb4c2",
      wood: "#8b5a2b",
      foliage: "#4bcf5a",
      foliageAlt: "#8fe36c",
      water: "#4cc3ff",
      roof: "#ff5c5c",
      wall: "#fff2d6",
      mushroom: "#ff4d6d",
      mushroomAlt: "#ffb703",
      glow: "#fff176",
      sky: "#8fd3ff",
    },
    tree: { style: "round", scale: [0.9, 1.4], rotationJitterDeg: 8, canopyLayers: [1, 2], trunkTaper: 0.5, hueJitterDeg: 15 },
    mushroom: { scaleMultiplier: [1.5, 3], capColors: ["#ff4d6d", "#ffb703", "#ff7b54"], glow: 0.05, spots: true },
    rock: { variation: "medium", clusterChance: 0.4, mossChance: 0.2 },
    architecture: { style: "timber_frame", roofPitch: 1.2, weathering: 0.05, scaleVariance: 0.3, chimneyChance: 0.9 },
    vegetationDensity: 0.55,
    propDensity: 0.5,
    lighting: { ambient: "#9fb8d6", outdoorAmbient: "#b7cce6", sunColor: "#ffffff", brightness: 2.6, shadowSoftness: 0.3, exposure: 0.25, colorCorrection: { saturation: 0.35, contrast: 0.12, tint: "#ffffff" } },
    fog: { start: 400, end: 2000, color: "#cfe9ff", atmosphereDensity: 0.15, haze: 0.5, glare: 0.6 },
  },
  dark_fantasy: {
    id: "dark_fantasy",
    name: "Dark Fantasy",
    geometry: "angular",
    palette: {
      primary: "#2b3a33",
      secondary: "#4a4f5c",
      accent: "#8f1f3f",
      ground: "#2f2620",
      stone: "#4d4f56",
      wood: "#3b2620",
      foliage: "#1f3327",
      foliageAlt: "#2f4a35",
      water: "#243544",
      roof: "#2e2530",
      wall: "#5c5247",
      mushroom: "#5a1f4a",
      mushroomAlt: "#7a2f3f",
      glow: "#ff3f6f",
      sky: "#2f3542",
    },
    tree: { style: "twisted", scale: [1.1, 2.0], rotationJitterDeg: 35, canopyLayers: [1, 3], trunkTaper: 0.8, hueJitterDeg: 6 },
    mushroom: { scaleMultiplier: [2, 5], capColors: ["#5a1f4a", "#7a2f3f", "#3f1f5a"], glow: 0.5, spots: true },
    rock: { variation: "high", clusterChance: 0.7, mossChance: 0.7 },
    architecture: { style: "ruined", roofPitch: 1.3, weathering: 0.9, scaleVariance: 0.3, chimneyChance: 0.3 },
    vegetationDensity: 0.65,
    propDensity: 0.45,
    lighting: { ambient: "#2f3442", outdoorAmbient: "#3a4050", sunColor: "#8f9bb8", brightness: 0.7, shadowSoftness: 0.85, exposure: -0.35, colorCorrection: { saturation: -0.3, contrast: 0.2, tint: "#c8d0ff" } },
    fog: { start: 30, end: 320, color: "#3f4656", atmosphereDensity: 0.55, haze: 2.4, glare: 0 },
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    geometry: "blocky",
    palette: {
      primary: "#1b1f3a",
      secondary: "#2f3556",
      accent: "#ff2bd6",
      ground: "#2a2a34",
      stone: "#4a4e5c",
      wood: "#3a3f4a",
      foliage: "#1f7a6a",
      foliageAlt: "#2fd0b0",
      water: "#1f3f66",
      roof: "#1f2233",
      wall: "#3a3f55",
      mushroom: "#00e5ff",
      mushroomAlt: "#ff2bd6",
      glow: "#00e5ff",
      sky: "#1a1533",
    },
    materials: { trunk: "Metal", canopy: "Neon", rock: "Concrete", wall: "Metal", stoneWall: "Concrete", roof: "Metal", path: "Asphalt", ground: "Asphalt", mushroom: "Neon", prop: "Metal", metal: "Metal" },
    tree: { style: "blocky", scale: [0.8, 1.4], rotationJitterDeg: 5, canopyLayers: [1, 2], trunkTaper: 0.9, hueJitterDeg: 20 },
    mushroom: { scaleMultiplier: [1, 3], capColors: ["#00e5ff", "#ff2bd6", "#7dff3b"], glow: 0.9, spots: false },
    rock: { variation: "low", clusterChance: 0.2, mossChance: 0 },
    architecture: { style: "cyber_block", roofPitch: 0.3, weathering: 0.4, scaleVariance: 0.4, chimneyChance: 0.1 },
    vegetationDensity: 0.2,
    propDensity: 0.7,
    lighting: { ambient: "#22203a", outdoorAmbient: "#2c2a4a", sunColor: "#6a5cff", brightness: 0.6, shadowSoftness: 0.6, exposure: -0.2, colorCorrection: { saturation: 0.2, contrast: 0.25, tint: "#d8c8ff" } },
    fog: { start: 80, end: 600, color: "#2a1f4a", atmosphereDensity: 0.5, haze: 2.0, glare: 0.3 },
  },
  desert: {
    id: "desert",
    name: "Desert",
    geometry: "chunky_low_poly",
    palette: {
      primary: "#c8a466",
      secondary: "#d9b98a",
      accent: "#c9563c",
      ground: "#c9a86a",
      stone: "#b08a5c",
      wood: "#8a6a44",
      foliage: "#6f8f4a",
      foliageAlt: "#8faa5a",
      water: "#4fa3c7",
      roof: "#a86a3f",
      wall: "#e2c9a0",
      mushroom: "#c9563c",
      mushroomAlt: "#d98c3c",
      glow: "#ffd98a",
      sky: "#9fd0ff",
    },
    materials: { trunk: "Wood", canopy: "Grass", rock: "Sandstone", wall: "Sandstone", stoneWall: "Sandstone", roof: "Wood", path: "Sand", ground: "Sand", mushroom: "SmoothPlastic", prop: "Wood", metal: "CorrodedMetal" },
    tree: { style: "round", scale: [0.8, 1.5], rotationJitterDeg: 15, canopyLayers: [1, 2], trunkTaper: 0.6, hueJitterDeg: 10 },
    mushroom: { scaleMultiplier: [0.8, 1.6], capColors: ["#c9563c", "#d98c3c"], glow: 0, spots: false },
    rock: { variation: "high", clusterChance: 0.5, mossChance: 0 },
    architecture: { style: "desert_adobe", roofPitch: 0.35, weathering: 0.5, scaleVariance: 0.3, chimneyChance: 0.2 },
    vegetationDensity: 0.18,
    propDensity: 0.4,
    lighting: { ambient: "#b6a58f", outdoorAmbient: "#c9b79f", sunColor: "#fff4e0", brightness: 3.0, shadowSoftness: 0.25, exposure: 0.2, colorCorrection: { saturation: 0.05, contrast: 0.1, tint: "#fff3e0" } },
    fog: { start: 300, end: 1600, color: "#e8d6b8", atmosphereDensity: 0.25, haze: 1.4, glare: 0.8 },
  },
  tropical: {
    id: "tropical",
    name: "Tropical",
    geometry: "smooth_low_poly",
    palette: {
      primary: "#3fa66b",
      secondary: "#6fc6d9",
      accent: "#ff6f61",
      ground: "#8a6a44",
      stone: "#8f8f8a",
      wood: "#7a4f2e",
      foliage: "#3f9f5a",
      foliageAlt: "#7fd06a",
      water: "#3fc1d9",
      roof: "#b78a4f",
      wall: "#e8dcc0",
      mushroom: "#ff6f61",
      mushroomAlt: "#ffb347",
      glow: "#fff0a0",
      sky: "#8fd8ff",
    },
    tree: { style: "round", scale: [1.0, 1.8], rotationJitterDeg: 20, canopyLayers: [2, 3], trunkTaper: 0.5, hueJitterDeg: 14 },
    mushroom: { scaleMultiplier: [1, 2], capColors: ["#ff6f61", "#ffb347"], glow: 0.05, spots: true },
    architecture: { style: "timber_frame", roofPitch: 0.7, weathering: 0.35, scaleVariance: 0.25, chimneyChance: 0.1 },
    vegetationDensity: 0.8,
    propDensity: 0.4,
    lighting: { ambient: "#9fc0d6", outdoorAmbient: "#b7d6ea", sunColor: "#fffaf0", brightness: 2.8, shadowSoftness: 0.35, exposure: 0.15, colorCorrection: { saturation: 0.25, contrast: 0.08, tint: "#ffffff" } },
    fog: { start: 300, end: 1500, color: "#cfeeff", atmosphereDensity: 0.2, haze: 0.8, glare: 0.5 },
  },
  winter: {
    id: "winter",
    name: "Winter",
    geometry: "chunky_low_poly",
    palette: {
      primary: "#dfe8f0",
      secondary: "#9fb4c8",
      accent: "#c94f4f",
      ground: "#e6edf3",
      stone: "#8d97a3",
      wood: "#5a4030",
      foliage: "#2f5a46",
      foliageAlt: "#3f7a5a",
      water: "#7fb3d5",
      roof: "#e8eef4",
      wall: "#7a5c44",
      mushroom: "#c94f4f",
      mushroomAlt: "#d98c8c",
      glow: "#ffe6a0",
      sky: "#b9cce0",
    },
    materials: { trunk: "Wood", canopy: "Grass", rock: "Slate", wall: "WoodPlanks", stoneWall: "Cobblestone", roof: "Snow", path: "Snow", ground: "Snow", mushroom: "SmoothPlastic", prop: "Wood", metal: "Metal" },
    tree: { style: "conifer", scale: [1.0, 1.9], rotationJitterDeg: 10, canopyLayers: [3, 5], trunkTaper: 0.75, hueJitterDeg: 6 },
    mushroom: { scaleMultiplier: [0.8, 1.5], capColors: ["#c94f4f"], glow: 0, spots: true },
    rock: { variation: "medium", clusterChance: 0.5, mossChance: 0 },
    architecture: { style: "nordic", roofPitch: 1.3, weathering: 0.4, scaleVariance: 0.2, chimneyChance: 0.9 },
    vegetationDensity: 0.5,
    propDensity: 0.45,
    lighting: { ambient: "#9db0c9", outdoorAmbient: "#b3c4da", sunColor: "#eef4ff", brightness: 1.6, shadowSoftness: 0.6, exposure: 0.05, colorCorrection: { saturation: -0.2, contrast: 0.05, tint: "#e6f0ff" } },
    fog: { start: 100, end: 700, color: "#d3dde8", atmosphereDensity: 0.4, haze: 2.0, glare: 0.2 },
  },
  swamp: {
    id: "swamp",
    name: "Swamp",
    geometry: "chunky_low_poly",
    palette: {
      primary: "#4a5a34",
      secondary: "#6b705c",
      accent: "#a0c23f",
      ground: "#3e3a2a",
      stone: "#6a6b62",
      wood: "#4a3626",
      foliage: "#3d5a2e",
      foliageAlt: "#5d7a3a",
      water: "#4a6a4f",
      roof: "#4d4a3a",
      wall: "#7d735f",
      mushroom: "#a0c23f",
      mushroomAlt: "#6f8f2f",
      glow: "#c8ff5a",
      sky: "#8a9a8a",
    },
    materials: { trunk: "Wood", canopy: "LeafyGrass", rock: "Slate", wall: "WoodPlanks", stoneWall: "Cobblestone", roof: "WoodPlanks", path: "Mud", ground: "Mud", mushroom: "SmoothPlastic", prop: "Wood", metal: "CorrodedMetal" },
    tree: { style: "twisted", scale: [1.0, 1.9], rotationJitterDeg: 30, canopyLayers: [2, 3], trunkTaper: 0.8, hueJitterDeg: 10 },
    mushroom: { scaleMultiplier: [1.5, 4], capColors: ["#a0c23f", "#6f8f2f", "#c8ff5a"], glow: 0.45, spots: true },
    rock: { variation: "medium", clusterChance: 0.5, mossChance: 0.9 },
    architecture: { style: "stone_hut", roofPitch: 0.8, weathering: 0.8, scaleVariance: 0.25, chimneyChance: 0.4 },
    vegetationDensity: 0.75,
    propDensity: 0.45,
    lighting: { ambient: "#5f6a58", outdoorAmbient: "#6f7a68", sunColor: "#d6dcc4", brightness: 1.0, shadowSoftness: 0.75, exposure: -0.15, colorCorrection: { saturation: -0.1, contrast: 0.1, tint: "#e0ffd8" } },
    fog: { start: 40, end: 380, color: "#7d8a73", atmosphereDensity: 0.55, haze: 2.5, glare: 0.05 },
  },
};

export const STYLE_PRESET_LIST: { id: StylePresetId; name: string; description: string }[] = [
  { id: "stylized_mystical", name: "Stylized Mystical", description: "Chunky low-poly, giant mushrooms, moonlit fog, desaturated greens and violets." },
  { id: "fantasy", name: "Fantasy", description: "Bright storybook fantasy with warm light and colorful foliage." },
  { id: "medieval", name: "Medieval", description: "Earthy, grounded, stone and timber, overcast light." },
  { id: "cartoon", name: "Cartoon", description: "Saturated, rounded shapes, high-key lighting." },
  { id: "dark_fantasy", name: "Dark Fantasy", description: "Twisted trees, ruins, deep fog, crimson glow." },
  { id: "cyberpunk", name: "Cyberpunk", description: "Neon, metal, asphalt, night city haze." },
  { id: "desert", name: "Desert", description: "Sandstone, adobe, harsh sun, sparse vegetation." },
  { id: "tropical", name: "Tropical", description: "Lush, turquoise water, bright sun." },
  { id: "winter", name: "Winter", description: "Snow, conifers, nordic cabins, cold light." },
  { id: "swamp", name: "Swamp", description: "Mud, twisted trees, glowing fungi, thick mist." },
];

export function getStylePreset(id: StylePresetId): StyleBible {
  return StyleBibleSchema.parse(PRESETS[id] ?? PRESETS.stylized_mystical);
}

export function getAllStylePresets(): StyleBible[] {
  return STYLE_PRESET_LIST.map((p) => getStylePreset(p.id));
}
