/**
 * UI strings — AUTO-GENERATED by scripts/sync-template.ts from the WorldForge taxonomy
 * (packages/core/src/taxonomy/ui-strings.ts). `GameConfig.ui.locale` selects the language; every
 * screen reads `L.<key>` so a translation never means touching the screens. A WorldForge
 * regeneration rewrites this file.
 */
import { GameConfig } from "shared/config";

export interface UiStringTable {
	shop: string;
	inventory: string;
	backpack: string;
	quests: string;
	crafting: string;
	craft: string;
	leaderboard: string;
	ranking: string;
	teams: string;
	settings: string;
	menu: string;
	resume: string;
	map: string;
	mapLoading: string;
	hunger: string;
	resources: string;
	consumables: string;
	upgrades: string;
	activeBuffs: string;
	inProgress: string;
	completed: string;
	audio: string;
	display: string;
	all: string;
	items: string;
	robux: string;
	buy: string;
	owned: string;
	claimed: string;
	confirmPurchase: string;
	confirmBuy: string;
	cancel: string;
	youHave: string;
	minutesLeft: string;
	gamePass: string;
	search: string;
	emptyBackpack: string;
	noRecipe: string;
	noQuest: string;
	consumable: string;
	resource: string;
	timeLeft: string;
	rankedBy: string;
	waitingPlayers: string;
	soloMode: string;
	phase: string;
	score: string;
	music: string;
	soundEffects: string;
	cameraShake: string;
	minimap: string;
	uiScale: string;
	settingsSaved: string;
	on: string;
	off: string;
	shapingWorld: string;
	common: string;
	uncommon: string;
	rare: string;
	epic: string;
	legendary: string;
}

export const UI_STRINGS: { [locale: string]: UiStringTable } = {
	en: {
		shop: "Shop",
		inventory: "Inventory",
		backpack: "Backpack",
		quests: "Quests",
		crafting: "Crafting",
		craft: "Craft",
		leaderboard: "Leaderboard",
		ranking: "Ranking",
		teams: "Teams",
		settings: "Settings",
		menu: "Menu",
		resume: "Resume",
		map: "MAP",
		mapLoading: "MAP — loading",
		hunger: "HUNGER",
		resources: "Resources",
		consumables: "Consumables",
		upgrades: "Upgrades",
		activeBuffs: "Active buffs",
		inProgress: "In progress",
		completed: "Completed",
		audio: "Audio",
		display: "Display",
		all: "All",
		items: "Items",
		robux: "Robux",
		buy: "Buy",
		owned: "Owned",
		claimed: "Claimed",
		confirmPurchase: "Confirm purchase",
		confirmBuy: "Buy {item} for {price} {currency}?",
		cancel: "Cancel",
		youHave: "You have: {count}",
		minutesLeft: "{minutes}m left",
		gamePass: "GAME PASS",
		search: "Search…",
		emptyBackpack: "Nothing yet — gather, farm or mine to fill the backpack.",
		noRecipe: "No recipe yet — add them to design/game.spec.json (crafting.recipes).",
		noQuest: "No quest in this game yet — add them to design/game.spec.json.",
		consumable: "Consumable",
		resource: "Resource",
		timeLeft: "{time} left",
		rankedBy: "Ranked by {stat}",
		waitingPlayers: "Waiting for players…",
		soloMode: "This mode is solo — see the leaderboard for the ranking.",
		phase: "Phase: {phase}",
		score: "Score",
		music: "Music",
		soundEffects: "Sound effects",
		cameraShake: "Camera shake",
		minimap: "Minimap",
		uiScale: "UI scale",
		settingsSaved: "Settings are saved with your profile and restored when you rejoin.",
		on: "ON",
		off: "OFF",
		shapingWorld: "Shaping the world…",
		common: "Common",
		uncommon: "Uncommon",
		rare: "Rare",
		epic: "Epic",
		legendary: "Legendary",
	},
	fr: {
		shop: "Boutique",
		inventory: "Inventaire",
		backpack: "Sac",
		quests: "Quêtes",
		crafting: "Artisanat",
		craft: "Fabriquer",
		leaderboard: "Classement",
		ranking: "Classement",
		teams: "Équipes",
		settings: "Réglages",
		menu: "Menu",
		resume: "Reprendre",
		map: "CARTE",
		mapLoading: "CARTE — chargement",
		hunger: "FAIM",
		resources: "Ressources",
		consumables: "Consommables",
		upgrades: "Améliorations",
		activeBuffs: "Bonus actifs",
		inProgress: "En cours",
		completed: "Terminées",
		audio: "Audio",
		display: "Affichage",
		all: "Tout",
		items: "Objets",
		robux: "Robux",
		buy: "Acheter",
		owned: "Obtenu",
		claimed: "Récupéré",
		confirmPurchase: "Confirmer l'achat",
		confirmBuy: "Acheter {item} pour {price} {currency} ?",
		cancel: "Annuler",
		youHave: "Vous en avez : {count}",
		minutesLeft: "{minutes} min restantes",
		gamePass: "PASS",
		search: "Rechercher…",
		emptyBackpack: "Rien pour l'instant — récoltez, cultivez ou minez pour remplir le sac.",
		noRecipe: "Aucune recette — ajoutez-les dans design/game.spec.json (crafting.recipes).",
		noQuest: "Aucune quête dans ce jeu — ajoutez-les dans design/game.spec.json.",
		consumable: "Consommable",
		resource: "Ressource",
		timeLeft: "{time} restant",
		rankedBy: "Classé par {stat}",
		waitingPlayers: "En attente de joueurs…",
		soloMode: "Ce mode est solo — voyez le classement pour le palmarès.",
		phase: "Phase : {phase}",
		score: "Score",
		music: "Musique",
		soundEffects: "Effets sonores",
		cameraShake: "Secousse caméra",
		minimap: "Minicarte",
		uiScale: "Taille de l'interface",
		settingsSaved: "Les réglages sont enregistrés avec votre profil et restaurés à la reconnexion.",
		on: "OUI",
		off: "NON",
		shapingWorld: "Création du monde…",
		common: "Commun",
		uncommon: "Peu commun",
		rare: "Rare",
		epic: "Épique",
		legendary: "Légendaire",
	},
	es: {
		shop: "Tienda",
		inventory: "Inventario",
		backpack: "Mochila",
		quests: "Misiones",
		crafting: "Fabricación",
		craft: "Fabricar",
		leaderboard: "Clasificación",
		ranking: "Clasificación",
		teams: "Equipos",
		settings: "Ajustes",
		menu: "Menú",
		resume: "Continuar",
		map: "MAPA",
		mapLoading: "MAPA — cargando",
		hunger: "HAMBRE",
		resources: "Recursos",
		consumables: "Consumibles",
		upgrades: "Mejoras",
		activeBuffs: "Mejoras activas",
		inProgress: "En curso",
		completed: "Completadas",
		audio: "Audio",
		display: "Pantalla",
		all: "Todo",
		items: "Objetos",
		robux: "Robux",
		buy: "Comprar",
		owned: "Obtenido",
		claimed: "Reclamado",
		confirmPurchase: "Confirmar compra",
		confirmBuy: "¿Comprar {item} por {price} {currency}?",
		cancel: "Cancelar",
		youHave: "Tienes: {count}",
		minutesLeft: "{minutes} min restantes",
		gamePass: "PASE",
		search: "Buscar…",
		emptyBackpack: "Nada aún — recoge, cultiva o mina para llenar la mochila.",
		noRecipe: "Sin recetas — añádelas en design/game.spec.json (crafting.recipes).",
		noQuest: "Sin misiones — añádelas en design/game.spec.json.",
		consumable: "Consumible",
		resource: "Recurso",
		timeLeft: "quedan {time}",
		rankedBy: "Ordenado por {stat}",
		waitingPlayers: "Esperando jugadores…",
		soloMode: "Este modo es individual — mira la clasificación.",
		phase: "Fase: {phase}",
		score: "Puntos",
		music: "Música",
		soundEffects: "Efectos de sonido",
		cameraShake: "Vibración de cámara",
		minimap: "Minimapa",
		uiScale: "Tamaño de la interfaz",
		settingsSaved: "Los ajustes se guardan con tu perfil y se restauran al volver.",
		on: "SÍ",
		off: "NO",
		shapingWorld: "Creando el mundo…",
		common: "Común",
		uncommon: "Poco común",
		rare: "Raro",
		epic: "Épico",
		legendary: "Legendario",
	},
	pt: {
		shop: "Loja",
		inventory: "Inventário",
		backpack: "Mochila",
		quests: "Missões",
		crafting: "Criação",
		craft: "Criar",
		leaderboard: "Classificação",
		ranking: "Ranking",
		teams: "Equipes",
		settings: "Configurações",
		menu: "Menu",
		resume: "Continuar",
		map: "MAPA",
		mapLoading: "MAPA — carregando",
		hunger: "FOME",
		resources: "Recursos",
		consumables: "Consumíveis",
		upgrades: "Melhorias",
		activeBuffs: "Bônus ativos",
		inProgress: "Em andamento",
		completed: "Concluídas",
		audio: "Áudio",
		display: "Tela",
		all: "Tudo",
		items: "Itens",
		robux: "Robux",
		buy: "Comprar",
		owned: "Adquirido",
		claimed: "Resgatado",
		confirmPurchase: "Confirmar compra",
		confirmBuy: "Comprar {item} por {price} {currency}?",
		cancel: "Cancelar",
		youHave: "Você tem: {count}",
		minutesLeft: "{minutes} min restantes",
		gamePass: "PASSE",
		search: "Pesquisar…",
		emptyBackpack: "Nada ainda — colete, plante ou minere para encher a mochila.",
		noRecipe: "Sem receitas — adicione em design/game.spec.json (crafting.recipes).",
		noQuest: "Sem missões — adicione em design/game.spec.json.",
		consumable: "Consumível",
		resource: "Recurso",
		timeLeft: "resta {time}",
		rankedBy: "Ordenado por {stat}",
		waitingPlayers: "Aguardando jogadores…",
		soloMode: "Este modo é solo — veja a classificação.",
		phase: "Fase: {phase}",
		score: "Pontos",
		music: "Música",
		soundEffects: "Efeitos sonoros",
		cameraShake: "Tremor de câmera",
		minimap: "Minimapa",
		uiScale: "Tamanho da interface",
		settingsSaved: "As configurações ficam salvas no seu perfil e voltam quando você entrar de novo.",
		on: "SIM",
		off: "NÃO",
		shapingWorld: "Criando o mundo…",
		common: "Comum",
		uncommon: "Incomum",
		rare: "Raro",
		epic: "Épico",
		legendary: "Lendário",
	},
	de: {
		shop: "Shop",
		inventory: "Inventar",
		backpack: "Rucksack",
		quests: "Quests",
		crafting: "Handwerk",
		craft: "Herstellen",
		leaderboard: "Rangliste",
		ranking: "Rangliste",
		teams: "Teams",
		settings: "Einstellungen",
		menu: "Menü",
		resume: "Weiter",
		map: "KARTE",
		mapLoading: "KARTE — lädt",
		hunger: "HUNGER",
		resources: "Rohstoffe",
		consumables: "Verbrauch",
		upgrades: "Upgrades",
		activeBuffs: "Aktive Boni",
		inProgress: "Laufend",
		completed: "Erledigt",
		audio: "Audio",
		display: "Anzeige",
		all: "Alle",
		items: "Gegenstände",
		robux: "Robux",
		buy: "Kaufen",
		owned: "Im Besitz",
		claimed: "Abgeholt",
		confirmPurchase: "Kauf bestätigen",
		confirmBuy: "{item} für {price} {currency} kaufen?",
		cancel: "Abbrechen",
		youHave: "Du hast: {count}",
		minutesLeft: "{minutes} Min. übrig",
		gamePass: "GAME PASS",
		search: "Suchen…",
		emptyBackpack: "Noch nichts — sammle, farme oder grabe, um den Rucksack zu füllen.",
		noRecipe: "Keine Rezepte — füge sie in design/game.spec.json hinzu (crafting.recipes).",
		noQuest: "Noch keine Quests — füge sie in design/game.spec.json hinzu.",
		consumable: "Verbrauchsgut",
		resource: "Rohstoff",
		timeLeft: "{time} übrig",
		rankedBy: "Sortiert nach {stat}",
		waitingPlayers: "Warte auf Spieler…",
		soloMode: "Dieser Modus ist Solo — siehe die Rangliste.",
		phase: "Phase: {phase}",
		score: "Punkte",
		music: "Musik",
		soundEffects: "Soundeffekte",
		cameraShake: "Kamerawackeln",
		minimap: "Minikarte",
		uiScale: "UI-Größe",
		settingsSaved: "Einstellungen werden im Profil gespeichert und beim nächsten Besuch geladen.",
		on: "AN",
		off: "AUS",
		shapingWorld: "Welt wird erschaffen…",
		common: "Gewöhnlich",
		uncommon: "Selten",
		rare: "Rar",
		epic: "Episch",
		legendary: "Legendär",
	},
};

export const UI_LOCALES: string[] = ["en", "fr", "es", "pt", "de"];

/** The table of the game's language (English for an unknown locale). */
export const L: UiStringTable = UI_STRINGS[(GameConfig.ui as { locale?: string }).locale ?? "en"] ?? UI_STRINGS.en!;

/** Fills `{name}` placeholders: `fmt(L.confirmBuy, { item: "Luck", price: 60, currency: "Coins" })`. */
export function fmt(template: string, values: { [key: string]: string | number }): string {
	let out = template;
	for (const [key, value] of pairs(values)) out = out.gsub(`{${key}}`, `${value}`, 1)[0];
	return out;
}
