import { UI_KITS, UI_LOCALES, UI_STRINGS, UI_STRINGS_EN, type UiKitDef } from "@worldforge/core";

/**
 * Generates `templates/roblox-ts-project/src/ui/kits.generated.ts`: the whole UI kit library as data
 * the project owns, so switching the look of a game is one field (`GameConfig.ui.kit`) and an agent can
 * tune the tokens in place. Source of truth: packages/core/src/taxonomy/ui-kits.ts.
 */
function kitEntry(kit: UiKitDef): string {
  const t = kit.tokens;
  const s = kit.shape;
  const hex = (v: string) => JSON.stringify(v);
  const pair = (v: [string, string]) => `[${hex(v[0])}, ${hex(v[1])}]`;
  return `\t${kit.id}: {
\t\tid: ${JSON.stringify(kit.id)},
\t\tname: ${JSON.stringify(kit.name)},
\t\tdescription: ${JSON.stringify(kit.description)},
\t\ttokens: {
\t\t\tpaper: ${hex(t.paper)},
\t\t\tpaperDark: ${hex(t.paperDark)},
\t\t\tink: ${hex(t.ink)},
\t\t\tinkSoft: ${hex(t.inkSoft)},
\t\t\ttext: ${hex(t.text)},
\t\t\ttextDark: ${hex(t.textDark)},
\t\t\tprimary: ${pair(t.primary)},
\t\t\tgold: ${pair(t.gold)},
\t\t\tdanger: ${pair(t.danger)},
\t\t\tinfo: ${pair(t.info)},
\t\t\tpill: ${hex(t.pill)},
\t\t\tpillStroke: ${hex(t.pillStroke)},
\t\t\ttile: ${hex(t.tile)},
\t\t\ttileStroke: ${hex(t.tileStroke)},
\t\t},
\t\tshape: {
\t\t\tradius: ${s.radius},
\t\t\tstrokeThickness: ${s.strokeThickness},
\t\t\tgradients: ${s.gradients ? "true" : "false"},
\t\t\tshadow: ${s.shadow},
\t\t\tshadowTransparency: ${s.shadowTransparency},
\t\t\tbevel: ${s.bevel ? "true" : "false"},
\t\t\ttextOutline: ${s.textOutline},
\t\t\tpanelTransparency: ${s.panelTransparency},
\t\t\tfont: Enum.Font.${s.font},
\t\t\tfontBody: Enum.Font.${s.fontBody},
\t\t\tornament: ${JSON.stringify(s.ornament)},
\t\t\tpress: ${JSON.stringify(s.press)},
\t\t\tenter: ${JSON.stringify(s.enter)},
\t\t\ttextScale: ${s.textScale},
\t\t\tsound: ${JSON.stringify(s.sound)},
\t\t\thover: ${JSON.stringify(s.hover)},
\t\t\tclickFx: ${JSON.stringify(s.clickFx)},
\t\t\trarityFx: ${JSON.stringify(s.rarityFx)},
\t\t\tmotion: ${s.motion},
\t\t},
\t},`;
}

export function buildUiKitsTs(): string {
  return `/**
 * UI kit library — AUTO-GENERATED by scripts/sync-template.ts from the WorldForge taxonomy
 * (packages/core/src/taxonomy/ui-kits.ts). Every kit is a complete design system; \`src/ui/kit.ts\`
 * renders the one \`GameConfig.ui.kit\` selects. Editing a kit here is fine (it is your project), but a
 * WorldForge regeneration rewrites this file — tune \`kit.ts\` or the GameSpec instead to keep changes.
 */

/** Decoration drawn on every panel of the kit (UI parts only, no image assets). */
export type UiOrnament = "none" | "rivets" | "scanlines" | "brackets" | "filigree" | "stripes" | "glow" | "grain" | "notch" | "stitch" | "chevrons" | "bubbles" | "grid";
/** Button feedback of the kit. */
export type UiPress = "squash" | "slide" | "flicker" | "pulse" | "none";
/** How a screen (kit.Window) appears. */
export type UiEnter = "pop" | "slide" | "fade" | "none";
/** Click feedback of the kit (built-in Roblox sounds). */
export type UiSound = "soft" | "click" | "beep" | "pop" | "thud" | "none";
/** Hover / selection feedback. */
export type UiHover = "lift" | "glow" | "tint" | "outline" | "none";
/** Click effect left at the cursor. */
export type UiClickFx = "ripple" | "burst" | "flash" | "none";
/** Rarity treatment of item tiles. */
export type UiRarityFx = "glow" | "sparkle" | "shine" | "none";

export interface UiKitTokens {
\tpaper: string;
\tpaperDark: string;
\tink: string;
\tinkSoft: string;
\ttext: string;
\ttextDark: string;
\tprimary: [string, string];
\tgold: [string, string];
\tdanger: [string, string];
\tinfo: [string, string];
\tpill: string;
\tpillStroke: string;
\ttile: string;
\ttileStroke: string;
}

export interface UiKitShape {
\tradius: number;
\tstrokeThickness: number;
\tgradients: boolean;
\tshadow: number;
\tshadowTransparency: number;
\tbevel: boolean;
\ttextOutline: number;
\tpanelTransparency: number;
\tfont: Enum.Font;
\tfontBody: Enum.Font;
\tornament: UiOrnament;
\tpress: UiPress;
\tenter: UiEnter;
\t/** multiplies every text size (decorative fonts need more room) */
\ttextScale: number;
\tsound: UiSound;
\thover: UiHover;
\tclickFx: UiClickFx;
\trarityFx: UiRarityFx;
\t/** animation intensity 0…1.4 (0 disables the looping effects) */
\tmotion: number;
}

export interface UiKit {
\tid: string;
\tname: string;
\tdescription: string;
\ttokens: UiKitTokens;
\tshape: UiKitShape;
}

export const UI_KITS: { [id: string]: UiKit } = {
${UI_KITS.map(kitEntry).join("\n")}
};

export const UI_KIT_IDS: string[] = [${UI_KITS.map((k) => JSON.stringify(k.id)).join(", ")}];

/** The kit every project falls back to when \`GameConfig.ui.kit\` names an unknown one. */
export const DEFAULT_UI_KIT = ${JSON.stringify(UI_KITS[0]!.id)};
`;
}

/**
 * Generates `templates/roblox-ts-project/src/ui/strings.generated.ts`: every label of the UI in the
 * supported languages. `GameConfig.ui.locale` picks the table; the screens read `L.<key>` and use
 * `fmt()` for the ones with placeholders. Source of truth: packages/core/src/taxonomy/ui-strings.ts.
 */
export function buildUiStringsTs(): string {
  const keys = Object.keys(UI_STRINGS_EN) as (keyof typeof UI_STRINGS_EN)[];
  const table = (locale: (typeof UI_LOCALES)[number]) =>
    `\t${locale}: {\n${keys.map((k) => `\t\t${k}: ${JSON.stringify(UI_STRINGS[locale][k])},`).join("\n")}\n\t},`;
  return `/**
 * UI strings — AUTO-GENERATED by scripts/sync-template.ts from the WorldForge taxonomy
 * (packages/core/src/taxonomy/ui-strings.ts). \`GameConfig.ui.locale\` selects the language; every
 * screen reads \`L.<key>\` so a translation never means touching the screens. A WorldForge
 * regeneration rewrites this file.
 */
import { GameConfig } from "shared/config";

export interface UiStringTable {
${keys.map((k) => `\t${k}: string;`).join("\n")}
}

export const UI_STRINGS: { [locale: string]: UiStringTable } = {
${UI_LOCALES.map(table).join("\n")}
};

export const UI_LOCALES: string[] = [${UI_LOCALES.map((l) => JSON.stringify(l)).join(", ")}];

/** The table of the game's language (English for an unknown locale). */
export const L: UiStringTable = UI_STRINGS[(GameConfig.ui as { locale?: string }).locale ?? "en"] ?? UI_STRINGS.en!;

/** Fills \`{name}\` placeholders: \`fmt(L.confirmBuy, { item: "Luck", price: 60, currency: "Coins" })\`. */
export function fmt(template: string, values: { [key: string]: string | number }): string {
\tlet out = template;
\tfor (const [key, value] of pairs(values)) out = out.gsub(\`{\${key}}\`, \`\${value}\`, 1)[0];
\treturn out;
}
`;
}
