// Generated by WorldForge from design/textures.manifest.json — do not edit (regenerate the textures instead).
export interface TextureEntry {
	id: string;
	baseMaterial: string;
	studsPerTile: number;
	/** Roblox image asset ids (0 = not uploaded yet → the base material stays as-is). */
	color: number;
	normal: number;
	roughness: number;
}

export const TextureSet: TextureEntry[] = [];
