/**
 * Embeds templates/roblox-ts-project/** into packages/roblox-export/src/template-files.generated.ts
 * so the exporter is self-contained (works inside the Tauri webview and in Node).
 *
 *   npx tsx scripts/sync-template.ts
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildUiKitsTs } from "../packages/roblox-export/src/uiKitFiles";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const templateDir = join(root, "templates", "roblox-ts-project");
const outFile = join(root, "packages", "roblox-export", "src", "template-files.generated.ts");

// the UI kit library is data: regenerate it from the taxonomy before embedding the template
const kitsFile = join(templateDir, "src", "ui", "kits.generated.ts");
const kitsTs = buildUiKitsTs();
if (!existsSync(kitsFile) || readFileSync(kitsFile, "utf8") !== kitsTs) {
  writeFileSync(kitsFile, kitsTs, "utf8");
  console.log(`regenerated ${relative(root, kitsFile)}`);
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === "out" || entry === "build") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(templateDir)
  .map((f) => relative(templateDir, f).replace(/\\/g, "/"))
  .sort();
const entries = files.map((rel) => {
  const content = readFileSync(join(templateDir, rel), "utf8");
  return `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`;
});
const header = `// AUTO-GENERATED by scripts/sync-template.ts — do not edit. Source: templates/roblox-ts-project/\n/* eslint-disable */\nexport const TEMPLATE_FILES: Record<string, string> = {\n`;
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + entries.join("\n") + "\n};\n", "utf8");
console.log(`embedded ${files.length} template files → ${relative(root, outFile)}`);
