/**
 * Embeds templates/roblox-ts-project/** into packages/roblox-export/src/template-files.generated.ts
 * so the exporter is self-contained (works inside the Tauri webview and in Node).
 *
 *   npx tsx scripts/sync-template.ts
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildUiKitsTs, buildUiStringsTs } from "../packages/roblox-export/src/uiKitFiles";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const templateDir = join(root, "templates", "roblox-ts-project");
const outFile = join(root, "packages", "roblox-export", "src", "template-files.generated.ts");

// the UI kit libraries and the UI strings are data: regenerate them before embedding the template
for (const [name, content] of [
  ["kits.generated.ts", buildUiKitsTs()],
  ["strings.generated.ts", buildUiStringsTs()],
] as const) {
  const file = join(templateDir, "src", "ui", name);
  if (!existsSync(file) || readFileSync(file, "utf8").replace(/\r\n/g, "\n") !== content) {
    writeFileSync(file, content, "utf8");
    console.log(`regenerated ${relative(root, file)}`);
  }
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === "out" || entry === "build") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(templateDir)
  .map((f) => relative(templateDir, f).replace(/\\/g, "/"))
  .sort();
const entries = files.map((rel) => {
  // LF inside the embedded strings whatever the checkout: these strings are written verbatim into
  // every generated project, and a CRLF payload would change what users compile (and breaks any
  // later rewrite of the generated module).
  const content = readFileSync(join(templateDir, rel), "utf8").replace(/\r\n/g, "\n");
  return `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`;
});
const header = `// AUTO-GENERATED by scripts/sync-template.ts — do not edit. Source: templates/roblox-ts-project/\n/* eslint-disable */\nexport const TEMPLATE_FILES: Record<string, string> = {\n`;
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + entries.join("\n") + "\n};\n", "utf8");
console.log(`embedded ${files.length} template files → ${relative(root, outFile)}`);
