import type { GenreDef } from "./types";

/**
 * Every Roblox game genre WorldForge can scaffold. `systems` are ids from GAMEPLAY_SYSTEMS (each has a
 * runtime module in the roblox-ts template), `layout` picks the map archetype the world generator lays
 * out on top of the terrain (obby course, arena, tycoon plots, race track, city grid…).
 */
export const GENRES: GenreDef[] = [
  {
    id: "survival",
    name: "Survival",
    description: "Gather, craft, manage hunger/thirst, survive nights and enemies.",
    keywords: ["survie", "survival", "survivre", "survive", "craft", "faim", "hunger", "zombie", "apocalypse", "ile deserte", "stranded"],
    systems: ["player_data", "currency", "inventory", "survival_stats", "collectibles", "crafting", "day_night", "combat", "weapons", "enemies", "quests", "npcs", "shop", "progression", "leaderboards"],
    layout: "open_world",
    screens: ["loading", "hud", "minimap", "inventory", "crafting", "quests", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "scrap",
    monetization: { passes: ["vip", "bigger_backpack"], products: ["coins_1000", "supply_drop"] },
    camera: "third_person",
    defaultStyles: ["post_apocalyptic", "realistic", "tropical", "stylized_mystical"],
    enemies: true,
    multiplayer: "open",
    progression: "unlock recipes and better gear; survive more nights; base upgrades",
  },
  {
    id: "adventure",
    name: "Adventure / Exploration",
    description: "Explore a rich world, talk to NPCs, complete quests, find secrets.",
    keywords: ["aventure", "adventure", "exploration", "explorer", "explore", "quete", "quest", "secret", "tresor", "decouvrir"],
    systems: ["player_data", "currency", "inventory", "collectibles", "quests", "npcs", "shop", "progression", "day_night"],
    layout: "open_world",
    screens: ["loading", "hud", "minimap", "inventory", "quests", "shop", "gamepass_shop", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "x2_coins"], products: ["coins_1000", "gem_pack"] },
    camera: "third_person",
    defaultStyles: ["stylized_mystical", "fantasy", "jungle", "elven"],
    enemies: false,
    multiplayer: "open",
    progression: "quest chain across regions; collectibles unlock areas and cosmetics",
  },
  {
    id: "rpg",
    name: "RPG",
    description: "Classes, levels, loot, dungeons, bosses and a quest line.",
    keywords: ["rpg", "jeu de role", "role play game", "classe", "class", "niveau", "level", "xp", "boss", "donjon", "dungeon", "loot", "mmo"],
    systems: ["player_data", "currency", "inventory", "quests", "npcs", "shop", "combat", "weapons", "enemies", "progression", "leaderboards", "day_night"],
    layout: "open_world",
    screens: ["loading", "hud", "minimap", "inventory", "quests", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "gold",
    monetization: { passes: ["vip", "x2_xp"], products: ["gold_1000", "legendary_chest"] },
    camera: "third_person",
    defaultStyles: ["fantasy", "medieval", "dark_fantasy", "feudal_japan"],
    enemies: true,
    multiplayer: "open",
    progression: "levels + stats, gear tiers, dungeons with bosses",
  },
  {
    id: "dungeon_crawler",
    name: "Dungeon Crawler",
    description: "Party up, clear procedurally laid-out dungeons room by room, beat the boss.",
    keywords: ["dungeon crawler", "donjon", "crypte", "crypt", "labyrinthe", "labyrinth", "raid", "roguelike", "rogue-like"],
    systems: ["player_data", "currency", "inventory", "combat", "weapons", "enemies", "rounds", "progression", "shop", "leaderboards"],
    layout: "dungeon",
    screens: ["loading", "hud", "round_status", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "gold",
    monetization: { passes: ["vip", "extra_life"], products: ["gold_1000", "legendary_chest"] },
    camera: "third_person",
    defaultStyles: ["dark_fantasy", "medieval", "horror_gothic", "ancient_egypt"],
    enemies: true,
    multiplayer: "solo_instances",
    progression: "floors get harder; persistent gear and gold",
  },
  {
    id: "obby",
    name: "Obby",
    description: "Platforming course with stages, checkpoints, kill bricks and a finish.",
    keywords: ["obby", "parcours", "obstacle", "plateforme", "platformer", "saut", "jump", "tower of hell", "checkpoint", "stage"],
    systems: ["player_data", "currency", "checkpoints", "obby", "shop", "leaderboards", "progression"],
    layout: "obby_course",
    screens: ["hud", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["skip_stage", "speed_coil", "vip"], products: ["skip_5_stages", "coins_500"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "low_poly_minimal", "candy", "sci_fi"],
    enemies: false,
    multiplayer: "open",
    progression: "stage counter, skips, trails and cosmetics",
  },
  {
    id: "parkour",
    name: "Parkour",
    description: "Rooftop running: wall runs, long jumps, timed routes across a city.",
    keywords: ["parkour", "freerun", "free run", "toits", "rooftop", "course d'obstacles urbaine", "sprint"],
    systems: ["player_data", "currency", "checkpoints", "parkour", "leaderboards", "shop", "progression"],
    layout: "city_grid",
    screens: ["hud", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "double_jump"], products: ["coins_500"] },
    camera: "third_person",
    defaultStyles: ["modern_city", "cyberpunk", "industrial", "post_apocalyptic"],
    enemies: false,
    multiplayer: "open",
    progression: "route times, unlockable moves and outfits",
  },
  {
    id: "tycoon",
    name: "Tycoon",
    description: "Own a plot, buy droppers and upgrades, expand your factory/base.",
    keywords: ["tycoon", "usine", "factory", "empire", "magnat", "dropper", "parcelle", "plot", "restaurant tycoon", "hotel tycoon", "theme park"],
    systems: ["player_data", "currency", "tycoon", "shop", "leaderboards", "progression"],
    layout: "tycoon_plots",
    screens: ["hud", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "cash",
    monetization: { passes: ["x2_cash", "auto_collect", "vip"], products: ["cash_10000", "cash_100000"] },
    camera: "third_person",
    defaultStyles: ["low_poly_minimal", "modern_city", "industrial", "cartoon"],
    enemies: false,
    multiplayer: "open",
    progression: "buttons unlock in tiers; rebirth multiplies income",
  },
  {
    id: "simulator",
    name: "Simulator",
    description: "Click/collect → sell → upgrade → rebirth loop with pets and zones.",
    keywords: ["simulator", "simulateur", "clicker", "click", "rebirth", "backpack", "sac", "vendre", "sell", "pet simulator", "bee", "mining simulator"],
    systems: ["player_data", "currency", "simulator_loop", "pets", "shop", "rng_rolls", "leaderboards", "progression"],
    layout: "hangout_plaza",
    screens: ["hud", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["x2_coins", "bigger_backpack", "vip"], products: ["coins_1000", "gem_pack", "lucky_egg"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "candy", "low_poly_minimal", "tropical"],
    enemies: false,
    multiplayer: "open",
    progression: "backpack/tool tiers, pets with multipliers, rebirths, new zones",
  },
  {
    id: "clicker",
    name: "Clicker / Idle",
    description: "Tap to earn, buy auto-clickers and multipliers, prestige.",
    keywords: ["idle", "incremental", "tap", "tapper", "auto click", "autoclick", "prestige"],
    systems: ["player_data", "currency", "clicker", "shop", "leaderboards", "progression"],
    layout: "hangout_plaza",
    screens: ["hud", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["x2_coins", "auto_click", "vip"], products: ["coins_1000", "coins_10000"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "candy", "low_poly_minimal"],
    enemies: false,
    multiplayer: "open",
    progression: "exponential upgrades and prestige resets",
  },
  {
    id: "pet_collecting",
    name: "Pet Collecting",
    description: "Hatch eggs, collect rare pets, trade and show them off.",
    keywords: ["pet", "animaux", "animal", "oeuf", "egg", "hatch", "eclore", "adopt", "adopt me", "collection", "rare"],
    systems: ["player_data", "currency", "pets", "rng_rolls", "trading", "shop", "collectibles", "leaderboards"],
    layout: "hangout_plaza",
    screens: ["hud", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "extra_pet_slots"], products: ["lucky_egg", "gem_pack"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "candy", "tropical", "fantasy"],
    enemies: false,
    multiplayer: "open",
    progression: "rarity tiers, golden/shiny variants, trading",
  },
  {
    id: "horror",
    name: "Horror",
    description: "Survive rounds against a monster in the dark; find keys, escape.",
    keywords: ["horreur", "horror", "peur", "scary", "monstre", "monster", "escape", "echapper", "doors", "piggy", "cache-cache horreur", "cauchemar", "nightmare"],
    systems: ["player_data", "currency", "rounds", "enemies", "puzzle", "day_night", "shop", "leaderboards"],
    layout: "linear_story",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "souls",
    monetization: { passes: ["vip", "flashlight_pro"], products: ["revive", "souls_500"] },
    camera: "first_person",
    defaultStyles: ["horror_gothic", "dark_fantasy", "post_apocalyptic", "industrial"],
    enemies: true,
    multiplayer: "rounds",
    progression: "unlock items for the next run; badges per escape",
  },
  {
    id: "roleplay",
    name: "Roleplay / Life Sim",
    description: "Town life: houses, jobs, vehicles, shops, hangouts (Brookhaven-like).",
    keywords: ["roleplay", "rp", "vie", "life", "brookhaven", "bloxburg", "ville rp", "maison", "house", "job", "metier", "famille", "family", "voiture", "car"],
    systems: ["player_data", "currency", "housing", "jobs", "vehicles", "shop", "npcs", "day_night", "inventory"],
    layout: "city_grid",
    screens: ["hud", "minimap", "inventory", "shop", "gamepass_shop", "settings", "menu"],
    currency: "cash",
    monetization: { passes: ["premium_house", "vip", "car_pack"], products: ["cash_1000", "cash_10000"] },
    camera: "third_person",
    defaultStyles: ["modern_suburban", "modern_city", "medieval", "feudal_japan"],
    enemies: false,
    multiplayer: "open",
    progression: "earn cash from jobs; buy houses, cars, furniture",
  },
  {
    id: "hangout",
    name: "Hangout / Social",
    description: "A beautiful place to chat, emote, take photos, play mini-activities.",
    keywords: ["hangout", "social", "chill", "detente", "discuter", "tchat", "spa", "cafe", "plage detente", "vibe", "lieu de rencontre"],
    systems: ["player_data", "currency", "collectibles", "shop", "npcs", "day_night"],
    layout: "hangout_plaza",
    screens: ["hud", "minimap", "shop", "gamepass_shop", "settings", "menu"],
    currency: "tokens",
    monetization: { passes: ["vip", "emote_pack"], products: ["tokens_500"] },
    camera: "third_person",
    defaultStyles: ["tropical", "modern_city", "cyberpunk", "candy"],
    enemies: false,
    multiplayer: "open",
    progression: "cosmetics and emotes",
  },
  {
    id: "battle",
    name: "Battle / PvP Arena",
    description: "Free-for-all or team fights in an arena with weapons and power-ups.",
    keywords: ["battle", "bataille", "pvp", "arene", "arena", "combat", "fight", "duel", "deathmatch", "sword fight", "bedwars"],
    systems: ["player_data", "currency", "combat", "weapons", "rounds", "teams", "matchmaking", "shop", "leaderboards"],
    layout: "arena",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "teams", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "weapon_skins"], products: ["coins_1000", "crate_key"] },
    camera: "third_person",
    defaultStyles: ["medieval", "sci_fi", "military", "feudal_japan"],
    enemies: false,
    multiplayer: "rounds",
    progression: "kills → coins → weapon tiers and skins",
  },
  {
    id: "battle_royale",
    name: "Battle Royale",
    description: "Drop in, loot, shrinking zone, last player standing.",
    keywords: ["battle royale", "br", "fortnite", "pubg", "zone", "dernier survivant", "last man standing", "loot"],
    systems: ["player_data", "currency", "combat", "weapons", "rounds", "matchmaking", "inventory", "shop", "leaderboards", "vehicles"],
    layout: "island",
    screens: ["hud", "round_status", "minimap", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "battle_pass"], products: ["coins_1000", "crate_key"] },
    camera: "third_person",
    defaultStyles: ["modern_suburban", "military", "tropical", "post_apocalyptic"],
    enemies: false,
    multiplayer: "rounds",
    progression: "wins and kills; battle pass cosmetics",
  },
  {
    id: "fps",
    name: "FPS / Shooter",
    description: "First-person gunplay, team objectives, loadouts.",
    keywords: ["fps", "shooter", "tir", "tireur", "gun", "arme a feu", "phantom forces", "arsenal", "call of duty", "counter strike"],
    systems: ["player_data", "currency", "combat", "weapons", "rounds", "teams", "capture_points", "matchmaking", "shop", "leaderboards"],
    layout: "arena",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "teams", "settings", "menu"],
    currency: "credits",
    monetization: { passes: ["vip", "weapon_skins"], products: ["credits_1000", "crate_key"] },
    camera: "first_person",
    defaultStyles: ["military", "modern_city", "industrial", "sci_fi"],
    enemies: false,
    multiplayer: "teams",
    progression: "rank ups unlock weapons and attachments",
  },
  {
    id: "tower_defense",
    name: "Tower Defense",
    description: "Waves of enemies walk a path; place and upgrade towers to stop them.",
    keywords: ["tower defense", "td", "defense", "vagues", "waves", "tours", "towers", "tds"],
    systems: ["player_data", "currency", "tower_defense", "enemies", "rounds", "shop", "leaderboards", "progression"],
    layout: "base_defense",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "x2_coins"], products: ["coins_1000", "tower_crate"] },
    camera: "top_down",
    defaultStyles: ["cartoon", "medieval", "sci_fi", "post_apocalyptic"],
    enemies: true,
    multiplayer: "solo_instances",
    progression: "tower unlocks, harder maps, wave records",
  },
  {
    id: "racing",
    name: "Racing",
    description: "Vehicles, a looping track with checkpoints, laps and best times.",
    keywords: ["course", "racing", "race", "voiture", "car", "kart", "moto", "circuit", "track", "drift", "vitesse", "speed"],
    systems: ["player_data", "currency", "vehicles", "racing", "shop", "leaderboards", "progression"],
    layout: "race_track",
    screens: ["hud", "minimap", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "car_pack"], products: ["coins_1000", "nitro_pack"] },
    camera: "third_person",
    defaultStyles: ["modern_city", "cartoon", "tropical", "cyberpunk"],
    enemies: false,
    multiplayer: "rounds",
    progression: "lap times unlock cars and upgrades",
  },
  {
    id: "sports",
    name: "Sports",
    description: "Football/basketball-style matches on a field with goals and scoring.",
    keywords: ["sport", "sports", "football", "soccer", "foot", "basket", "basketball", "stade", "stadium", "match", "but", "goal"],
    systems: ["player_data", "currency", "sports", "teams", "rounds", "matchmaking", "shop", "leaderboards"],
    layout: "sports_field",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "teams", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "kit_pack"], products: ["coins_1000"] },
    camera: "third_person",
    defaultStyles: ["modern_city", "modern_suburban", "cartoon", "low_poly_minimal"],
    enemies: false,
    multiplayer: "teams",
    progression: "match wins, player ratings, kits",
  },
  {
    id: "fighting",
    name: "Fighting",
    description: "1v1 duels with combos, blocking, abilities and ranked ladders.",
    keywords: ["fighting", "baston", "combattant", "1v1", "duel", "combo", "arts martiaux", "martial arts", "boxe", "boxing", "tekken", "the strongest battlegrounds"],
    systems: ["player_data", "currency", "combat", "abilities", "rounds", "matchmaking", "shop", "leaderboards", "progression"],
    layout: "arena",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "character_pack"], products: ["coins_1000"] },
    camera: "third_person",
    defaultStyles: ["feudal_japan", "modern_city", "cyberpunk", "ancient_greece"],
    enemies: false,
    multiplayer: "rounds",
    progression: "ranked ladder, unlock characters and moves",
  },
  {
    id: "puzzle",
    name: "Puzzle / Escape",
    description: "Rooms with switches, keys, pressure plates and doors to solve.",
    keywords: ["puzzle", "enigme", "casse-tete", "escape room", "escape game", "cle", "key", "levier", "switch", "porte", "riddle"],
    systems: ["player_data", "currency", "puzzle", "checkpoints", "collectibles", "leaderboards"],
    layout: "linear_story",
    screens: ["hud", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "stars",
    monetization: { passes: ["vip", "hints"], products: ["skip_puzzle"] },
    camera: "third_person",
    defaultStyles: ["ancient_egypt", "sci_fi", "steampunk", "jungle"],
    enemies: false,
    multiplayer: "solo_instances",
    progression: "chapters unlock in order; stars per chapter",
  },
  {
    id: "story",
    name: "Story / Narrative",
    description: "Guided linear experience with cutscene-like dialogue and set pieces.",
    keywords: ["histoire", "story", "narratif", "narrative", "scenario", "chapitre", "chapter", "dialogue", "cinematique"],
    systems: ["player_data", "story", "npcs", "quests", "checkpoints", "collectibles"],
    layout: "linear_story",
    screens: ["loading", "hud", "quests", "gamepass_shop", "settings", "menu"],
    currency: "stars",
    monetization: { passes: ["vip"], products: ["skip_chapter"] },
    camera: "third_person",
    defaultStyles: ["stylized_mystical", "realistic", "horror_gothic", "post_apocalyptic"],
    enemies: false,
    multiplayer: "solo_instances",
    progression: "chapters and endings",
  },
  {
    id: "sandbox",
    name: "Sandbox / Building",
    description: "Free building on plots with a part/furniture catalogue.",
    keywords: ["sandbox", "construction", "building", "construire", "build", "creatif", "creative", "plot", "terrain constructible", "bac a sable"],
    systems: ["player_data", "currency", "building", "housing", "shop", "inventory"],
    layout: "tycoon_plots",
    screens: ["hud", "minimap", "inventory", "shop", "gamepass_shop", "settings", "menu"],
    currency: "cash",
    monetization: { passes: ["vip", "bigger_plot"], products: ["cash_10000"] },
    camera: "free",
    defaultStyles: ["low_poly_minimal", "voxel", "modern_suburban", "cartoon"],
    enemies: false,
    multiplayer: "open",
    progression: "unlock more items and bigger plots",
  },
  {
    id: "farming",
    name: "Farming",
    description: "Plant seeds, water, harvest, sell crops, raise animals (Grow a Garden-like).",
    keywords: ["ferme", "farm", "farming", "jardin", "garden", "grow a garden", "planter", "plant", "recolte", "harvest", "culture", "crops", "animaux de ferme"],
    systems: ["player_data", "currency", "farming", "shop", "inventory", "day_night", "leaderboards", "trading"],
    layout: "tycoon_plots",
    screens: ["hud", "minimap", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "x2_growth"], products: ["coins_1000", "rare_seed_pack"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "fantasy", "realistic", "low_poly_minimal"],
    enemies: false,
    multiplayer: "open",
    progression: "seed tiers, plot expansions, mutations",
  },
  {
    id: "mining",
    name: "Mining",
    description: "Dig ore, upgrade pickaxes, sell, explore deeper caves.",
    keywords: ["mine", "mining", "minage", "miner", "pioche", "pickaxe", "minerai", "ore", "caverne", "cave", "creuser", "dig"],
    systems: ["player_data", "currency", "mining", "shop", "inventory", "progression", "leaderboards"],
    layout: "open_world",
    screens: ["hud", "minimap", "inventory", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "x2_ore"], products: ["coins_1000", "dynamite_pack"] },
    camera: "third_person",
    defaultStyles: ["voxel", "cartoon", "realistic", "wild_west"],
    enemies: false,
    multiplayer: "open",
    progression: "pickaxe tiers and deeper layers",
  },
  {
    id: "minigames",
    name: "Minigames / Party",
    description: "Rotating quick games (hide & seek, sword race, king of the hill) from a lobby.",
    keywords: ["minigame", "mini-jeu", "mini jeux", "party", "epic minigames", "cache-cache", "hide and seek", "king of the hill", "lobby"],
    systems: ["player_data", "currency", "rounds", "minigames", "matchmaking", "shop", "leaderboards"],
    layout: "lobby_portals",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "coins",
    monetization: { passes: ["vip", "x2_coins"], products: ["coins_1000"] },
    camera: "third_person",
    defaultStyles: ["cartoon", "candy", "low_poly_minimal", "tropical"],
    enemies: false,
    multiplayer: "rounds",
    progression: "coins for wins → cosmetics",
  },
  {
    id: "strategy",
    name: "Strategy / Base Building",
    description: "Gather resources, build a base, train units, defend and attack.",
    keywords: ["strategie", "strategy", "rts", "base", "armee", "unites", "units", "ressources", "resources", "conquete", "conquer", "civilisation"],
    systems: ["player_data", "currency", "building", "tower_defense", "enemies", "rounds", "progression", "leaderboards"],
    layout: "base_defense",
    screens: ["hud", "round_status", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "gold",
    monetization: { passes: ["vip", "x2_gold"], products: ["gold_1000"] },
    camera: "top_down",
    defaultStyles: ["medieval", "viking", "sci_fi", "ancient_greece"],
    enemies: true,
    multiplayer: "solo_instances",
    progression: "tech tiers and stronger waves",
  },
  {
    id: "rhythm",
    name: "Rhythm / Music",
    description: "Hit notes to the beat on a stage with lights and crowd.",
    keywords: ["rythme", "rhythm", "musique", "music", "beat", "danse", "dance", "concert", "dj", "robeats", "notes"],
    systems: ["player_data", "currency", "rhythm", "shop", "leaderboards"],
    layout: "hangout_plaza",
    screens: ["hud", "shop", "gamepass_shop", "leaderboard", "settings", "menu"],
    currency: "notes",
    monetization: { passes: ["vip", "song_pack"], products: ["notes_1000"] },
    camera: "third_person",
    defaultStyles: ["cyberpunk", "candy", "modern_city", "cartoon"],
    enemies: false,
    multiplayer: "open",
    progression: "scores per song, unlock songs and stages",
  },
];

export const GENRE_INDEX: Record<string, GenreDef> = Object.fromEntries(GENRES.map((g) => [g.id, g]));
export const GENRE_IDS = GENRES.map((g) => g.id);
