import type { StyleFamilyDef } from "./types";

/** Modern, future, apocalyptic and themed style families. */
export const STYLE_FAMILIES_B: StyleFamilyDef[] = [
  {
    id: "modern_suburban",
    name: "Modern Suburban",
    description: "Present-day neighbourhood: houses with gardens, asphalt roads, cars, streetlights.",
    group: "modern",
    keywords: ["moderne", "modern", "banlieue", "suburb", "suburban", "quartier", "neighborhood", "neighbourhood", "maison moderne", "brookhaven", "pavillon", "residential"],
    geometry: "angular",
    palette: { primary: "#6a9a5a", secondary: "#8a8a90", accent: "#3a7ad0", ground: "#5a6a3a", stone: "#909090", wood: "#8a6a48", foliage: "#4a9a48", foliageAlt: "#7ab858", water: "#3a90c0", roof: "#4a4a50", wall: "#e8e4dc", glow: "#fff0c0", sky: "#8ac0f0" },
    materials: { wall: "Concrete", stoneWall: "Brick", roof: "Slate", path: "Asphalt", ground: "Grass", prop: "Plastic", metal: "Metal" },
    tree: "round",
    architecture: { kit: "modern_house", roofPitch: 0.6, weathering: 0.15, chimneyChance: 0.4, interiors: true, floors: [1, 2] },
    vegetationKit: "temperate",
    vegetationDensity: 0.4,
    propKits: ["suburban", "urban", "playground"],
    roadKit: "asphalt_road",
    biomes: ["meadow", "forest", "beach"],
    landmarks: ["tower", "statue", "well"],
    settlementType: "town",
    lighting: { timeOfDay: 14, mood: "bright", ambient: "#9aa0a8", outdoorAmbient: "#b0b8c0", sunColor: "#fff8f0", brightness: 2.3, exposure: 0.05, saturation: 0.05, contrast: 0.05, tint: "#ffffff" },
    fog: { start: 300, end: 2000, color: "#c8d8ea", density: 0.12, haze: 0.6, glare: 0.3 },
    ui: "modern",
    uiAccent: "#3a7ad0",
    audio: "chill",
  },
  {
    id: "modern_city",
    name: "Modern City",
    description: "Downtown: skyscrapers, apartment blocks, wide streets, plazas, neon signs at night.",
    group: "modern",
    keywords: ["ville", "city", "urbain", "urban", "downtown", "gratte-ciel", "skyscraper", "metropole", "metropolis", "centre-ville", "immeuble", "building", "new york", "tokyo", "paris"],
    geometry: "angular",
    palette: { primary: "#6a7a8a", secondary: "#9aa0a8", accent: "#ff6a3a", ground: "#5a5a5a", stone: "#8a8a8a", wood: "#7a6a58", foliage: "#4a8a48", foliageAlt: "#6aa858", water: "#3a80b0", roof: "#3a3a40", wall: "#b8c0c8", glow: "#8ad0ff", sky: "#8ab8e0" },
    materials: { wall: "Concrete", stoneWall: "Concrete", roof: "Metal", path: "Asphalt", ground: "Concrete", prop: "Metal", metal: "Metal", rock: "Concrete" },
    tree: "round",
    architecture: { kit: "apartment_block", roofPitch: 0.1, weathering: 0.2, chimneyChance: 0, interiors: true, floors: [3, 8] },
    vegetationKit: "temperate",
    vegetationDensity: 0.15,
    propKits: ["urban", "industrial"],
    roadKit: "asphalt_road",
    biomes: ["urban", "meadow"],
    landmarks: ["skyscraper", "fountain", "statue", "stadium"],
    settlementType: "city_district",
    lighting: { timeOfDay: 15, mood: "soft", ambient: "#8890a0", outdoorAmbient: "#a0a8b8", sunColor: "#fff4ea", brightness: 2.1, exposure: 0, saturation: 0, contrast: 0.08, tint: "#fbfbff" },
    fog: { start: 250, end: 1800, color: "#c0ccd8", density: 0.18, haze: 1.0, glare: 0.25 },
    ui: "modern",
    uiAccent: "#ff6a3a",
    audio: "chill",
  },
  {
    id: "industrial",
    name: "Industrial Zone",
    description: "Factories, warehouses, silos, pipes, containers and cranes under a hazy sky.",
    group: "modern",
    keywords: ["industriel", "industrial", "usine", "factory", "entrepot", "warehouse", "port industriel", "docks industriels", "conteneur", "container", "raffinerie", "refinery"],
    geometry: "angular",
    palette: { primary: "#6a6a68", secondary: "#8a8078", accent: "#e0a020", ground: "#5a5850", stone: "#808080", wood: "#6a5a48", foliage: "#5a7a40", foliageAlt: "#7a9050", water: "#4a6a70", roof: "#5a5a5a", wall: "#8a8a88", glow: "#ffd060", sky: "#9aa0a8" },
    materials: { wall: "Metal", stoneWall: "Concrete", roof: "CorrodedMetal", path: "Asphalt", ground: "Concrete", metal: "DiamondPlate", rock: "Concrete" },
    tree: "round",
    architecture: { kit: "industrial_shed", roofPitch: 0.25, weathering: 0.6, chimneyChance: 0.7, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.12,
    propKits: ["industrial", "urban", "military"],
    roadKit: "concrete_road",
    biomes: ["urban", "wasteland", "meadow"],
    landmarks: ["radio_tower", "water_tower", "tower"],
    settlementType: "city_district",
    lighting: { timeOfDay: 16.5, mood: "overcast", ambient: "#7a7a78", outdoorAmbient: "#909088", sunColor: "#f0e8d8", brightness: 1.6, exposure: -0.05, saturation: -0.2, contrast: 0.1, tint: "#f0eee8" },
    fog: { start: 120, end: 1000, color: "#a8a8a0", density: 0.35, haze: 1.8, glare: 0.2 },
    ui: "military",
    uiAccent: "#e0a020",
    audio: "industrial",
  },
  {
    id: "post_apocalyptic",
    name: "Post-Apocalyptic",
    description: "Zombie/collapse aftermath: wrecked cars, barricades, overgrown ruins, crashed planes, grey sky.",
    group: "apocalyptic",
    keywords: ["apocalypse", "apocalyptique", "post-apo", "zombie", "zombi", "infecte", "infected", "survie zombie", "epidemie", "outbreak", "abandonne", "abandoned", "ruine moderne", "the last of us", "fin du monde"],
    geometry: "angular",
    palette: { primary: "#5a6a4a", secondary: "#7a7870", accent: "#c04a2a", ground: "#5a5a48", stone: "#7a7a74", wood: "#6a5a44", foliage: "#5a7a3a", foliageAlt: "#8a9a4a", water: "#4a5a58", roof: "#4a4a48", wall: "#a8a49a", glow: "#ffb060", sky: "#8a9098" },
    materials: { wall: "Concrete", stoneWall: "Brick", roof: "CorrodedMetal", path: "Asphalt", ground: "Ground", metal: "CorrodedMetal", rock: "Concrete" },
    tree: "twisted",
    architecture: { kit: "modern_house", roofPitch: 0.6, weathering: 0.9, chimneyChance: 0.3, interiors: true, floors: [1, 2] },
    vegetationKit: "dead",
    vegetationDensity: 0.55,
    propKits: ["apocalypse", "suburban", "military", "camp"],
    roadKit: "asphalt_road",
    biomes: ["wasteland", "forest", "dark_forest", "ruins_field", "meadow"],
    landmarks: ["crashed_plane", "radio_tower", "skyscraper_ruin", "water_tower", "campfire"],
    settlementType: "abandoned_village",
    lighting: { timeOfDay: 17, mood: "overcast", ambient: "#6a7078", outdoorAmbient: "#808890", sunColor: "#d8d8d0", brightness: 1.3, exposure: -0.15, saturation: -0.3, contrast: 0.12, tint: "#e8e8e0" },
    fog: { start: 60, end: 700, color: "#8a9098", density: 0.5, haze: 2.4, glare: 0.1 },
    ui: "military",
    uiAccent: "#c04a2a",
    audio: "tense",
  },
  {
    id: "wasteland",
    name: "Desert Wasteland",
    description: "Mad-Max style scorched desert: scrap forts, rusted vehicles, dust storms.",
    group: "apocalyptic",
    keywords: ["wasteland", "terres desolees", "mad max", "desert post-apo", "scrap", "ferraille", "nucleaire", "nuclear", "fallout", "radioactif"],
    geometry: "angular",
    palette: { primary: "#b08a50", secondary: "#8a7a68", accent: "#d05020", ground: "#b89058", stone: "#a08060", wood: "#6a5038", foliage: "#7a7a40", foliageAlt: "#9a9050", water: "#7a8a70", roof: "#6a5a48", wall: "#8a7a68", glow: "#ffa040", sky: "#d0b080" },
    materials: { wall: "CorrodedMetal", stoneWall: "Concrete", roof: "CorrodedMetal", path: "Ground", ground: "Sand", metal: "CorrodedMetal", rock: "Sandstone" },
    tree: "twisted",
    architecture: { kit: "shack", roofPitch: 0.3, weathering: 1.0, chimneyChance: 0.4, interiors: true },
    vegetationKit: "desert",
    vegetationDensity: 0.15,
    propKits: ["apocalypse", "industrial", "camp", "military"],
    roadKit: "sand_path",
    biomes: ["desert", "wasteland", "rocky"],
    landmarks: ["radio_tower", "water_tower", "crashed_plane", "mountain_peak"],
    settlementType: "base",
    lighting: { timeOfDay: 16, mood: "golden", ambient: "#a08a68", outdoorAmbient: "#b8a080", sunColor: "#ffd090", brightness: 2.2, exposure: 0, saturation: -0.05, contrast: 0.12, tint: "#ffe0b0" },
    fog: { start: 120, end: 1200, color: "#d8b888", density: 0.35, haze: 2.0, glare: 0.5 },
    ui: "military",
    uiAccent: "#d05020",
    audio: "tense",
  },
  {
    id: "sci_fi",
    name: "Sci-Fi Colony",
    description: "Clean futuristic base: white modules, glass domes, blue energy lights, hover pads.",
    group: "future",
    keywords: ["sci-fi", "scifi", "science fiction", "futuriste", "futuristic", "futur", "future", "colonie", "colony", "base spatiale", "laser", "robot", "android", "hologramme"],
    geometry: "smooth_low_poly",
    palette: { primary: "#4a7a9a", secondary: "#d8e0e8", accent: "#30c0ff", ground: "#6a6a70", stone: "#8a8a90", wood: "#8a8a90", foliage: "#3a9a8a", foliageAlt: "#60c0a0", water: "#30a0d0", roof: "#c8d0d8", wall: "#e8ecf0", glow: "#40d0ff", sky: "#80b0e0" },
    materials: { wall: "SmoothPlastic", stoneWall: "Metal", roof: "Metal", path: "Metal", ground: "Slate", prop: "Metal", metal: "Metal", rock: "Slate" },
    tree: "round",
    architecture: { kit: "scifi_module", roofPitch: 0.1, weathering: 0.05, chimneyChance: 0, interiors: true, floors: [1, 3] },
    vegetationKit: "alien",
    vegetationDensity: 0.3,
    propKits: ["scifi", "space", "industrial"],
    roadKit: "metal_walkway",
    biomes: ["rocky", "meadow", "alien", "highlands"],
    landmarks: ["rocket", "dome_base", "radio_tower", "portal"],
    settlementType: "base",
    lighting: { timeOfDay: 14, mood: "bright", ambient: "#8898b0", outdoorAmbient: "#a0b0c8", sunColor: "#f0f8ff", brightness: 2.2, exposure: 0.05, saturation: 0.05, contrast: 0.1, tint: "#f0f8ff" },
    fog: { start: 250, end: 1800, color: "#b8d0e8", density: 0.15, haze: 0.8, glare: 0.4 },
    ui: "sci-fi",
    uiAccent: "#30c0ff",
    audio: "electronic",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Rainy neon megacity at night: dense blocks, holograms, pink/cyan glow, wet asphalt.",
    group: "future",
    keywords: ["cyberpunk", "neon", "neons", "megacity", "night city", "blade runner", "hacker", "synthwave", "dystopie", "dystopian"],
    geometry: "angular",
    palette: { primary: "#2a2a44", secondary: "#4a3a6a", accent: "#ff3fa0", ground: "#1a1a2a", stone: "#3a3a4a", wood: "#4a3a3a", foliage: "#2a5a5a", foliageAlt: "#3a8a7a", water: "#1a3a5a", roof: "#2a2a34", wall: "#3a3a50", mushroom: "#ff3fa0", mushroomAlt: "#3fd0ff", glow: "#3fd0ff", sky: "#1a1030" },
    materials: { wall: "Metal", stoneWall: "Concrete", roof: "Metal", path: "Asphalt", ground: "Asphalt", prop: "Metal", metal: "Metal", rock: "Concrete" },
    tree: "blocky",
    architecture: { kit: "cyber_block", roofPitch: 0.1, weathering: 0.5, chimneyChance: 0, interiors: true, floors: [3, 9] },
    vegetationKit: "none",
    vegetationDensity: 0.05,
    propKits: ["cyber", "urban", "industrial"],
    roadKit: "neon_road",
    biomes: ["urban", "wasteland"],
    landmarks: ["skyscraper", "portal", "radio_tower", "statue"],
    settlementType: "city_district",
    lighting: { timeOfDay: 22, mood: "moonlit", ambient: "#30284a", outdoorAmbient: "#3a3060", sunColor: "#8080c0", brightness: 0.6, exposure: -0.2, saturation: 0.2, contrast: 0.2, tint: "#e0d0ff" },
    fog: { start: 40, end: 500, color: "#2a1a44", density: 0.5, haze: 2.5, glare: 0.6 },
    ui: "sci-fi",
    uiAccent: "#ff3fa0",
    audio: "electronic",
  },
  {
    id: "space_station",
    name: "Space Station / Moon",
    description: "Grey regolith, craters, sealed modules, antennas, black starry sky.",
    group: "future",
    keywords: ["espace", "space", "lune", "moon", "mars", "station spatiale", "space station", "astronaute", "astronaut", "planete", "planet", "cratere", "crater", "orbite"],
    geometry: "angular",
    palette: { primary: "#7a7a80", secondary: "#a0a0a8", accent: "#ff9030", ground: "#6a6a70", stone: "#808088", wood: "#8a8a90", foliage: "#5a6a70", foliageAlt: "#7a8a90", water: "#2a3a50", roof: "#c0c0c8", wall: "#d0d0d8", glow: "#ffa040", sky: "#05050c" },
    materials: { wall: "Metal", stoneWall: "Metal", roof: "Metal", path: "Metal", ground: "Slate", prop: "Metal", metal: "Metal", rock: "Slate" },
    tree: "blocky",
    architecture: { kit: "scifi_module", roofPitch: 0.1, weathering: 0.2, chimneyChance: 0, interiors: true, floors: [1, 2] },
    vegetationKit: "none",
    vegetationDensity: 0,
    propKits: ["space", "scifi"],
    roadKit: "metal_walkway",
    biomes: ["moon", "rocky"],
    landmarks: ["rocket", "dome_base", "radio_tower", "mountain_peak", "ufo"],
    settlementType: "base",
    lighting: { timeOfDay: 12, mood: "bright", ambient: "#404048", outdoorAmbient: "#505058", sunColor: "#ffffff", brightness: 3.0, exposure: 0, saturation: -0.1, contrast: 0.2, tint: "#ffffff" },
    fog: { start: 800, end: 4000, color: "#08080f", density: 0.02, haze: 0.1, glare: 0.6 },
    ui: "sci-fi",
    uiAccent: "#ff9030",
    audio: "electronic",
  },
  {
    id: "alien_planet",
    name: "Alien Planet",
    description: "Purple/teal alien flora, glowing crystals, twin-moon sky, strange rock spires.",
    group: "future",
    keywords: ["alien", "extraterrestre", "planete alien", "exoplanete", "xeno", "pandora", "avatar", "monde alien"],
    geometry: "smooth_low_poly",
    palette: { primary: "#4a3a7a", secondary: "#6a5a9a", accent: "#40ffd0", ground: "#4a3a5a", stone: "#6a5a8a", wood: "#5a3a6a", foliage: "#6a3aa0", foliageAlt: "#3fc0b0", water: "#40c0c0", roof: "#3a2a5a", wall: "#8a7ab0", mushroom: "#40ffd0", mushroomAlt: "#ff60c0", glow: "#60ffe0", sky: "#3a2060" },
    materials: { ground: "Slate", rock: "Basalt", canopy: "Neon" },
    tree: "twisted",
    architecture: { kit: "scifi_module", roofPitch: 0.1, weathering: 0.3, chimneyChance: 0, interiors: true },
    vegetationKit: "alien",
    vegetationDensity: 0.7,
    propKits: ["scifi", "space", "forest"],
    roadKit: "metal_walkway",
    biomes: ["alien", "rocky", "highlands", "dark_forest"],
    landmarks: ["crystal_spire", "portal", "dome_base", "ufo"],
    settlementType: "outpost",
    lighting: { timeOfDay: 19, mood: "dusk", ambient: "#503a70", outdoorAmbient: "#604a80", sunColor: "#d0a0ff", brightness: 1.4, exposure: -0.05, saturation: 0.25, contrast: 0.12, tint: "#e8d8ff" },
    fog: { start: 100, end: 900, color: "#4a2a70", density: 0.4, haze: 1.8, glare: 0.4 },
    mushrooms: 0.4,
    ui: "sci-fi",
    uiAccent: "#40ffd0",
    audio: "mystical",
  },
  {
    id: "horror_gothic",
    name: "Gothic Horror",
    description: "Haunted mansion grounds: dead trees, graveyards, fog, lightning, candle light.",
    group: "themed",
    keywords: ["horreur", "horror", "gothique", "gothic", "manoir", "mansion", "hante", "haunted", "fantome", "ghost", "vampire", "cimetiere", "graveyard", "halloween", "epouvante", "creepy", "scary"],
    geometry: "angular",
    palette: { primary: "#2a2a30", secondary: "#4a4a54", accent: "#c03030", ground: "#2a2824", stone: "#4a4a50", wood: "#3a2a24", foliage: "#2a3a2a", foliageAlt: "#3a4a34", water: "#1a2a30", roof: "#2a2430", wall: "#5a5a60", glow: "#ff9040", sky: "#202030" },
    materials: { wall: "Brick", stoneWall: "Cobblestone", roof: "Slate", path: "Cobblestone", ground: "Mud" },
    tree: "twisted",
    architecture: { kit: "gothic", roofPitch: 1.4, weathering: 0.85, chimneyChance: 0.8, interiors: true, floors: [2, 3] },
    vegetationKit: "dead",
    vegetationDensity: 0.45,
    propKits: ["graveyard", "horror", "ruins"],
    roadKit: "cobblestone_road",
    biomes: ["dark_forest", "swamp", "ruins_field", "meadow"],
    landmarks: ["castle", "tower", "statue", "ruins", "well"],
    settlementType: "abandoned_village",
    lighting: { timeOfDay: 23, mood: "stormy", ambient: "#303040", outdoorAmbient: "#383848", sunColor: "#7080a0", brightness: 0.5, exposure: -0.3, saturation: -0.4, contrast: 0.2, tint: "#c8d0e8" },
    fog: { start: 25, end: 300, color: "#303038", density: 0.7, haze: 3, glare: 0 },
    ui: "horror",
    uiAccent: "#c03030",
    audio: "horror",
  },
  {
    id: "tropical",
    name: "Tropical Island",
    description: "Turquoise lagoons, white sand, palms, bamboo huts, bright sun.",
    group: "nature",
    keywords: ["tropical", "ile", "island", "plage", "beach", "lagon", "lagoon", "paradis", "paradise", "hawai", "palmier", "palm", "vacances", "resort"],
    geometry: "chunky_low_poly",
    palette: { primary: "#3aa070", secondary: "#f0e0b0", accent: "#ff8040", ground: "#e0d0a0", stone: "#a09880", wood: "#8a6a40", foliage: "#3ab060", foliageAlt: "#8ad060", water: "#30d0d0", roof: "#c0a060", wall: "#e8d8b0", glow: "#ffe080", sky: "#70c8ff" },
    materials: { ground: "Sand", path: "Sand", roof: "Grass", wall: "WoodPlanks" },
    tree: "round",
    architecture: { kit: "tropical_hut", roofPitch: 0.9, weathering: 0.3, chimneyChance: 0, interiors: true },
    vegetationKit: "tropical",
    vegetationDensity: 0.6,
    propKits: ["tropical", "docks", "camp"],
    roadKit: "sand_path",
    biomes: ["beach", "forest", "meadow", "rocky"],
    landmarks: ["lighthouse", "volcano", "temple", "campfire", "statue"],
    settlementType: "village",
    lighting: { timeOfDay: 13, mood: "bright", ambient: "#a0a8b0", outdoorAmbient: "#b8c0c8", sunColor: "#fffaf0", brightness: 2.6, exposure: 0.1, saturation: 0.2, contrast: 0.06, tint: "#fffaf0" },
    fog: { start: 350, end: 2200, color: "#c8ecff", density: 0.1, haze: 0.5, glare: 0.5 },
    ui: "cartoon",
    uiAccent: "#ff8040",
    audio: "tropical",
  },
  {
    id: "jungle",
    name: "Jungle Temple",
    description: "Dense rainforest, giant leaves, vines, mossy ruins and hidden temples.",
    group: "nature",
    keywords: ["jungle", "foret tropicale", "rainforest", "amazon", "amazonie", "temple perdu", "lost temple", "aztec", "azteque", "maya", "inca", "tomb raider", "explorateur"],
    geometry: "chunky_low_poly",
    palette: { primary: "#2a7a3a", secondary: "#6a8a4a", accent: "#ffb020", ground: "#3a3a24", stone: "#6a7a60", wood: "#5a4a30", foliage: "#2a8a3a", foliageAlt: "#60c040", water: "#3a8a80", roof: "#5a6a3a", wall: "#8a9a70", mushroom: "#c0a030", glow: "#ffe060", sky: "#80c0e0" },
    materials: { ground: "LeafyGrass", stoneWall: "Cobblestone", wall: "Cobblestone", roof: "Grass", path: "Ground" },
    tree: "round",
    architecture: { kit: "stone_hut", roofPitch: 0.8, weathering: 0.8, chimneyChance: 0, interiors: true },
    vegetationKit: "jungle",
    vegetationDensity: 0.9,
    propKits: ["jungle", "ruins", "camp"],
    roadKit: "dirt_path",
    biomes: ["jungle", "forest", "swamp", "rocky"],
    landmarks: ["pyramid", "temple", "giant_tree", "statue", "waterfall_cliff"],
    settlementType: "camp",
    lighting: { timeOfDay: 14, mood: "soft", ambient: "#6a8a6a", outdoorAmbient: "#809a80", sunColor: "#f0ffe0", brightness: 1.9, exposure: 0, saturation: 0.15, contrast: 0.08, tint: "#f0fff0" },
    fog: { start: 80, end: 700, color: "#7aa080", density: 0.4, haze: 1.6, glare: 0.3 },
    ui: "fantasy",
    uiAccent: "#ffb020",
    audio: "ambient_nature",
  },
  {
    id: "desert",
    name: "Desert Oasis",
    description: "Dunes, adobe villages, oases and sandstone canyons.",
    group: "nature",
    keywords: ["desert", "sable", "dune", "oasis", "canyon", "sahara", "aride", "arid", "bedouin"],
    geometry: "angular",
    palette: { primary: "#c8a060", secondary: "#a08060", accent: "#2f8fbf", ground: "#c8a868", stone: "#b08858", wood: "#8a6a40", foliage: "#6a8a3a", foliageAlt: "#8aa850", water: "#3aa0b0", roof: "#b08860", wall: "#d8b888", glow: "#ffd070", sky: "#a8d0f0" },
    materials: { wall: "Sandstone", stoneWall: "Sandstone", roof: "Sandstone", path: "Sand", ground: "Sand", rock: "Sandstone" },
    tree: "round",
    architecture: { kit: "desert_adobe", roofPitch: 0.3, weathering: 0.5, chimneyChance: 0.2, interiors: true },
    vegetationKit: "desert",
    vegetationDensity: 0.2,
    propKits: ["village", "camp", "farm"],
    roadKit: "sand_path",
    biomes: ["desert", "rocky", "meadow"],
    landmarks: ["temple", "well", "mountain_peak", "ruins"],
    lighting: { timeOfDay: 13, mood: "golden", ambient: "#a0988a", outdoorAmbient: "#b8b0a0", sunColor: "#fff2d0", brightness: 2.6, exposure: 0.1, saturation: 0.1, contrast: 0.08, tint: "#fff4e0" },
    fog: { start: 300, end: 2000, color: "#e8d8b8", density: 0.12, haze: 0.9, glare: 0.5 },
    ui: "fantasy",
    uiAccent: "#2f8fbf",
    audio: "western",
  },
  {
    id: "winter",
    name: "Winter / Arctic",
    description: "Snowy pines, frozen lakes, igloos and log cabins, blue-white light.",
    group: "nature",
    keywords: ["neige", "snow", "hiver", "winter", "glace", "ice", "arctique", "arctic", "polaire", "polar", "igloo", "noel", "christmas", "ski", "toundra", "tundra"],
    geometry: "chunky_low_poly",
    palette: { primary: "#e8f0f8", secondary: "#8aa0b8", accent: "#ff8040", ground: "#e8eef4", stone: "#8890a0", wood: "#5a4030", foliage: "#3a6a4a", foliageAlt: "#5a8a6a", water: "#5a90c0", roof: "#f0f4f8", wall: "#8a6a48", glow: "#ffe0a0", sky: "#b8d0e8" },
    materials: { ground: "Snow", path: "Snow", roof: "Snow", rock: "Ice" },
    tree: "conifer",
    architecture: { kit: "nordic", roofPitch: 1.2, weathering: 0.4, chimneyChance: 0.9, interiors: true },
    vegetationKit: "arctic",
    vegetationDensity: 0.45,
    propKits: ["arctic", "camp", "village"],
    roadKit: "snow_path",
    biomes: ["snow", "pine_forest", "tundra", "rocky"],
    landmarks: ["mountain_peak", "campfire", "tower", "statue"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 14.5, mood: "overcast", ambient: "#a0b0c8", outdoorAmbient: "#b8c8d8", sunColor: "#f0f8ff", brightness: 2.0, exposure: 0.05, saturation: -0.1, contrast: 0.05, tint: "#eef4ff" },
    fog: { start: 150, end: 1200, color: "#d8e4f0", density: 0.3, haze: 1.2, glare: 0.35 },
    ui: "minimal",
    uiAccent: "#ff8040",
    audio: "chill",
  },
  {
    id: "swamp",
    name: "Swamp",
    description: "Murky water, willows, reeds, stilt huts, green fog and fireflies.",
    group: "nature",
    keywords: ["marais", "swamp", "marecage", "bog", "bayou", "mangrove", "tourbiere"],
    geometry: "chunky_low_poly",
    palette: { primary: "#3a5a3a", secondary: "#6a7a5a", accent: "#a0d040", ground: "#3a3a28", stone: "#5a6a58", wood: "#4a3a28", foliage: "#3a6a34", foliageAlt: "#6a8a40", water: "#3a5a48", roof: "#4a4a34", wall: "#7a6a50", mushroom: "#7a9a3a", mushroomAlt: "#9a7a3a", glow: "#c0ff60", sky: "#7a8a80" },
    materials: { ground: "Mud", path: "WoodPlanks", roof: "Grass" },
    tree: "twisted",
    architecture: { kit: "stone_hut", roofPitch: 0.8, weathering: 0.8, chimneyChance: 0.3, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.7,
    propKits: ["docks", "camp", "graveyard"],
    roadKit: "wooden_walkway",
    biomes: ["swamp", "dark_forest", "forest"],
    landmarks: ["giant_tree", "ruins", "well", "statue"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 18, mood: "eerie", ambient: "#5a6a58", outdoorAmbient: "#6a7a68", sunColor: "#c0d0b0", brightness: 1.1, exposure: -0.15, saturation: -0.1, contrast: 0.1, tint: "#e0f0d8" },
    fog: { start: 40, end: 400, color: "#5a6a58", density: 0.6, haze: 2.4, glare: 0.1 },
    mushrooms: 0.25,
    ui: "stylized",
    uiAccent: "#a0d040",
    audio: "ambient_nature",
  },
  {
    id: "underwater",
    name: "Underwater",
    description: "Ocean-floor world: coral reefs, kelp, sunken ships, blue caustic light.",
    group: "themed",
    keywords: ["sous-marin", "underwater", "ocean", "mer", "sea", "corail", "coral", "atlantide", "atlantis", "sirene", "mermaid", "abysse", "abyss", "aquatique"],
    geometry: "rounded",
    palette: { primary: "#2a6a8a", secondary: "#4a8aa0", accent: "#ff7a50", ground: "#c8b890", stone: "#6a8a90", wood: "#5a4a38", foliage: "#3aa080", foliageAlt: "#ff6080", water: "#1a6090", roof: "#4a9ab0", wall: "#8ab0c0", mushroom: "#ff7a50", mushroomAlt: "#ffc050", glow: "#60ffd0", sky: "#0a3a60" },
    materials: { ground: "Sand", rock: "Slate", wall: "Marble", roof: "Marble" },
    tree: "round",
    architecture: { kit: "greek_temple", roofPitch: 0.4, weathering: 0.7, chimneyChance: 0, interiors: true },
    vegetationKit: "coral",
    vegetationDensity: 0.7,
    propKits: ["underwater", "pirate", "ruins"],
    roadKit: "sand_path",
    biomes: ["ocean_floor", "beach", "rocky"],
    landmarks: ["pirate_ship", "ruins", "statue", "temple", "crystal_spire"],
    settlementType: "outpost",
    lighting: { timeOfDay: 12, mood: "soft", ambient: "#2a5a80", outdoorAmbient: "#3a6a90", sunColor: "#80c0e0", brightness: 1.2, exposure: -0.1, saturation: 0.1, contrast: 0.1, tint: "#a0d0ff" },
    fog: { start: 20, end: 260, color: "#0a4a70", density: 0.7, haze: 3, glare: 0.2 },
    ui: "cartoon",
    uiAccent: "#ff7a50",
    audio: "ambient_nature",
  },
  {
    id: "candy",
    name: "Candy Land",
    description: "Lollipop trees, chocolate rivers, gingerbread houses, pastel skies.",
    group: "themed",
    keywords: ["candy", "bonbon", "sucre", "sugar", "chocolat", "chocolate", "pain d'epice", "gingerbread", "sucette", "lollipop", "gateau", "cake", "pastel"],
    geometry: "rounded",
    palette: { primary: "#ff9ad0", secondary: "#a0e0ff", accent: "#ff4a8a", ground: "#f0d0a0", stone: "#ffd0e0", wood: "#8a4a2a", foliage: "#7ae090", foliageAlt: "#ffb0e0", water: "#8a4a2a", roof: "#ff6a9a", wall: "#c07a4a", mushroom: "#ff6a9a", mushroomAlt: "#ffd050", glow: "#ffffa0", sky: "#ffd0f0" },
    materials: { ground: "Grass", path: "SmoothPlastic", wall: "SmoothPlastic", roof: "SmoothPlastic", rock: "SmoothPlastic", trunk: "SmoothPlastic" },
    tree: "round",
    architecture: { kit: "candy", roofPitch: 1.0, weathering: 0, chimneyChance: 0.7, interiors: true },
    vegetationKit: "candy",
    vegetationDensity: 0.55,
    propKits: ["candy", "playground", "carnival"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "beach"],
    landmarks: ["giant_tree", "windmill", "ferris_wheel", "statue"],
    lighting: { timeOfDay: 12, mood: "bright", ambient: "#c0b0c8", outdoorAmbient: "#d0c8d8", sunColor: "#fff8ff", brightness: 2.6, exposure: 0.15, saturation: 0.4, contrast: 0.05, tint: "#fff4ff" },
    fog: { start: 300, end: 1800, color: "#ffd8f0", density: 0.1, haze: 0.4, glare: 0.5 },
    ui: "candy",
    uiAccent: "#ff4a8a",
    audio: "cheerful",
  },
  {
    id: "low_poly_minimal",
    name: "Low-Poly Minimal",
    description: "Flat-shaded pastel minimalism: simple blocks, few colours, clean light.",
    group: "themed",
    keywords: ["low poly", "low-poly", "lowpoly", "minimal", "minimaliste", "flat", "simple", "epure", "clean"],
    geometry: "blocky",
    palette: { primary: "#7ab890", secondary: "#c8d0d8", accent: "#f0a040", ground: "#a0c070", stone: "#b0b8c0", wood: "#b08a60", foliage: "#7ac080", foliageAlt: "#a8d890", water: "#70c0e0", roof: "#f07050", wall: "#f4f0e8", glow: "#fff0a0", sky: "#b0d8f8" },
    materials: { trunk: "SmoothPlastic", canopy: "SmoothPlastic", rock: "SmoothPlastic", wall: "SmoothPlastic", stoneWall: "SmoothPlastic", roof: "SmoothPlastic", path: "SmoothPlastic", ground: "Grass", prop: "SmoothPlastic", metal: "SmoothPlastic" },
    tree: "blocky",
    architecture: { kit: "modern_house", roofPitch: 0.8, weathering: 0, chimneyChance: 0.5, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.45,
    propKits: ["village", "suburban", "playground"],
    roadKit: "stone_path",
    biomes: ["meadow", "forest", "beach", "highlands"],
    landmarks: ["windmill", "tower", "statue", "well"],
    lighting: { timeOfDay: 13, mood: "bright", ambient: "#b0b8c0", outdoorAmbient: "#c8d0d8", sunColor: "#ffffff", brightness: 2.4, exposure: 0.1, saturation: 0.1, contrast: 0.02, tint: "#ffffff" },
    fog: { start: 400, end: 2400, color: "#d8e8f8", density: 0.06, haze: 0.2, glare: 0.3 },
    ui: "minimal",
    uiAccent: "#f0a040",
    audio: "chill",
  },
  {
    id: "voxel",
    name: "Voxel / Blocky",
    description: "Cube-world look: blocky trees, cube hills, pixel-like palette.",
    group: "themed",
    keywords: ["voxel", "cube", "cubique", "blocky", "minecraft", "pixel", "8-bit", "retro blocks"],
    geometry: "blocky",
    palette: { primary: "#5a9a3a", secondary: "#8a8a8a", accent: "#e0a020", ground: "#7a5a3a", stone: "#8a8a8a", wood: "#8a6a3a", foliage: "#4aa030", foliageAlt: "#70c040", water: "#3a70d0", roof: "#8a4a2a", wall: "#d8c8a0", glow: "#ffe060", sky: "#80b8f8" },
    materials: { trunk: "Wood", canopy: "Grass", rock: "Slate", wall: "WoodPlanks", stoneWall: "Cobblestone", roof: "WoodPlanks", path: "Cobblestone", ground: "Grass", prop: "Wood", metal: "Metal" },
    tree: "blocky",
    architecture: { kit: "voxel", roofPitch: 0.9, weathering: 0.1, chimneyChance: 0.5, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.5,
    propKits: ["village", "mine", "farm"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "highlands", "desert", "snow"],
    landmarks: ["tower", "castle", "well", "mountain_peak"],
    lighting: { timeOfDay: 12.5, mood: "bright", ambient: "#a0a8b0", outdoorAmbient: "#b8c0c8", sunColor: "#ffffff", brightness: 2.3, exposure: 0.08, saturation: 0.2, contrast: 0.06, tint: "#ffffff" },
    fog: { start: 300, end: 1600, color: "#c0d8f8", density: 0.12, haze: 0.4, glare: 0.3 },
    ui: "retro",
    uiAccent: "#e0a020",
    audio: "retro",
  },
  {
    id: "military",
    name: "Military Base",
    description: "Camo greens, sandbags, watchtowers, barracks, hangars and vehicles.",
    group: "modern",
    keywords: ["militaire", "military", "armee", "army", "base militaire", "guerre", "war", "soldat", "soldier", "fps", "caserne", "barracks", "bunker", "combat zone"],
    geometry: "angular",
    palette: { primary: "#5a6a4a", secondary: "#7a7a6a", accent: "#d0a030", ground: "#6a6a4a", stone: "#8a8a80", wood: "#6a5a40", foliage: "#4a7a3a", foliageAlt: "#6a9a4a", water: "#4a6a70", roof: "#4a5a40", wall: "#7a8a6a", glow: "#ffd060", sky: "#98a8b8" },
    materials: { wall: "Concrete", stoneWall: "Concrete", roof: "Metal", path: "Asphalt", ground: "Ground", metal: "DiamondPlate" },
    tree: "conifer",
    architecture: { kit: "bunker", roofPitch: 0.2, weathering: 0.5, chimneyChance: 0.1, interiors: true },
    vegetationKit: "conifer",
    vegetationDensity: 0.35,
    propKits: ["military", "industrial", "camp"],
    roadKit: "concrete_road",
    biomes: ["meadow", "pine_forest", "desert", "rocky", "wasteland"],
    landmarks: ["radio_tower", "tower", "water_tower", "campfire"],
    settlementType: "base",
    lighting: { timeOfDay: 15, mood: "overcast", ambient: "#8a9088", outdoorAmbient: "#a0a8a0", sunColor: "#f0f0e8", brightness: 1.8, exposure: -0.05, saturation: -0.15, contrast: 0.1, tint: "#f0f4ee" },
    fog: { start: 200, end: 1400, color: "#b0b8b8", density: 0.25, haze: 1.2, glare: 0.2 },
    ui: "military",
    uiAccent: "#d0a030",
    audio: "tense",
  },
];
