import type { StyleFamilyDef } from "./types";

/**
 * Biome-led style families (tropical, jungle, desert, winter, swamp, underwater) and the themed looks
 * that are a rendering choice rather than a place (cartoon, candy, low-poly, voxel, military…).
 * Grouped by the `group` field, so a new style has an obvious home.
 */
export const STYLE_FAMILIES_NATURE: StyleFamilyDef[] = [
  {
    id: "realistic",
    name: "Realistic Nature",
    description: "Natural palette, realistic proportions, subtle light — forests, lakes, mountains.",
    group: "nature",
    keywords: ["realiste", "realistic", "realism", "nature", "naturel", "photoreal", "montagne", "mountain", "lac", "lake", "randonnee"],
    geometry: "smooth_low_poly",
    palette: { primary: "#4a6a3a", secondary: "#7a7a78", accent: "#c08040", ground: "#5a4a34", stone: "#7a7874", wood: "#5a4030", foliage: "#3f6a34", foliageAlt: "#6a8a40", water: "#3a6a80", roof: "#5a4a40", wall: "#b0a088", glow: "#ffe0b0", sky: "#8ab8e0" },
    tree: "conifer",
    architecture: { kit: "modern_house", roofPitch: 0.7, weathering: 0.3, chimneyChance: 0.5, interiors: true },
    vegetationKit: "conifer",
    vegetationDensity: 0.7,
    propKits: ["camp", "forest", "farm"],
    roadKit: "dirt_path",
    biomes: ["pine_forest", "forest", "meadow", "highlands", "rocky"],
    landmarks: ["mountain_peak", "campfire", "tower", "well"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 15, mood: "soft", ambient: "#8890a0", outdoorAmbient: "#a0a8b8", sunColor: "#fff4e4", brightness: 2.0, exposure: 0, saturation: -0.05, contrast: 0.06, tint: "#fbf8f4" },
    fog: { start: 250, end: 2000, color: "#c0d0e0", density: 0.18, haze: 0.8, glare: 0.25 },
    ui: "minimal",
    uiAccent: "#c08040",
    audio: "ambient_nature",
    weather: "none", clouds: 0.45, walls: "none", terrainTint: 0.25,
  },
  {
    id: "tropical",
    name: "Tropical Island",
    description: "Turquoise lagoons, white sand, palms, bamboo huts, bright sun.",
    group: "nature",
    keywords: ["tropical", "ile", "island", "plage", "beach", "lagon", "lagoon", "paradis", "paradise", "hawai", "palmier", "palm", "vacances", "resort"],
    geometry: "chunky_low_poly",
    palette: { primary: "#3aa070", secondary: "#f0e0b0", accent: "#ff8040", ground: "#e0d0a0", stone: "#a09880", wood: "#8a6a40", foliage: "#3ab060", foliageAlt: "#8ad060", water: "#30d0d0", roof: "#c0a060", wall: "#e8d8b0", glow: "#ffe080", sky: "#70c8ff" },
    materials: { ground: "Sand", path: "Sand", roof: "Grass", wall: "WoodPlanks" },
    tree: "round",
    architecture: { kit: "tropical_hut", roofPitch: 0.9, weathering: 0.3, chimneyChance: 0, interiors: true },
    vegetationKit: "tropical",
    vegetationDensity: 0.6,
    propKits: ["tropical", "docks", "camp"],
    roadKit: "sand_path",
    biomes: ["beach", "forest", "meadow", "rocky"],
    landmarks: ["lighthouse", "volcano", "temple", "campfire", "statue"],
    settlementType: "village",
    lighting: { timeOfDay: 13, mood: "bright", ambient: "#a0a8b0", outdoorAmbient: "#b8c0c8", sunColor: "#fffaf0", brightness: 2.6, exposure: 0.1, saturation: 0.2, contrast: 0.06, tint: "#fffaf0" },
    fog: { start: 350, end: 2200, color: "#c8ecff", density: 0.1, haze: 0.5, glare: 0.5 },
    ui: "cartoon",
    uiAccent: "#ff8040",
    audio: "tropical",
    weather: "none", clouds: 0.3, walls: "none", terrainTint: 0.6,
  },
  {
    id: "jungle",
    name: "Jungle Temple",
    description: "Dense rainforest, giant leaves, vines, mossy ruins and hidden temples.",
    group: "nature",
    keywords: ["jungle", "foret tropicale", "rainforest", "amazon", "amazonie", "temple perdu", "lost temple", "aztec", "azteque", "maya", "inca", "tomb raider", "explorateur"],
    geometry: "chunky_low_poly",
    palette: { primary: "#2a7a3a", secondary: "#6a8a4a", accent: "#ffb020", ground: "#3a3a24", stone: "#6a7a60", wood: "#5a4a30", foliage: "#2a8a3a", foliageAlt: "#60c040", water: "#3a8a80", roof: "#5a6a3a", wall: "#8a9a70", mushroom: "#c0a030", glow: "#ffe060", sky: "#80c0e0" },
    materials: { ground: "LeafyGrass", stoneWall: "Cobblestone", wall: "Cobblestone", roof: "Grass", path: "Ground" },
    tree: "round",
    architecture: { kit: "stone_hut", roofPitch: 0.8, weathering: 0.8, chimneyChance: 0, interiors: true },
    vegetationKit: "jungle",
    vegetationDensity: 0.9,
    propKits: ["jungle", "ruins", "camp"],
    roadKit: "dirt_path",
    biomes: ["jungle", "forest", "swamp", "rocky"],
    landmarks: ["pyramid", "temple", "giant_tree", "statue", "waterfall_cliff"],
    settlementType: "camp",
    lighting: { timeOfDay: 14, mood: "soft", ambient: "#6a8a6a", outdoorAmbient: "#809a80", sunColor: "#f0ffe0", brightness: 1.9, exposure: 0, saturation: 0.15, contrast: 0.08, tint: "#f0fff0" },
    fog: { start: 80, end: 700, color: "#7aa080", density: 0.4, haze: 1.6, glare: 0.3 },
    ui: "fantasy",
    uiAccent: "#ffb020",
    audio: "ambient_nature",
    weather: "fireflies", weatherIntensity: 0.4, clouds: 0.5, walls: "bamboo", terrainTint: 0.65,
  },
  {
    id: "desert",
    name: "Desert Oasis",
    description: "Dunes, adobe villages, oases and sandstone canyons.",
    group: "nature",
    keywords: ["desert", "sable", "dune", "oasis", "canyon", "sahara", "aride", "arid", "bedouin"],
    geometry: "angular",
    palette: { primary: "#c8a060", secondary: "#a08060", accent: "#2f8fbf", ground: "#c8a868", stone: "#b08858", wood: "#8a6a40", foliage: "#6a8a3a", foliageAlt: "#8aa850", water: "#3aa0b0", roof: "#b08860", wall: "#d8b888", glow: "#ffd070", sky: "#a8d0f0" },
    materials: { wall: "Sandstone", stoneWall: "Sandstone", roof: "Sandstone", path: "Sand", ground: "Sand", rock: "Sandstone" },
    tree: "round",
    architecture: { kit: "desert_adobe", roofPitch: 0.3, weathering: 0.5, chimneyChance: 0.2, interiors: true },
    vegetationKit: "desert",
    vegetationDensity: 0.2,
    propKits: ["village", "camp", "farm"],
    roadKit: "sand_path",
    biomes: ["desert", "rocky", "meadow"],
    landmarks: ["temple", "well", "mountain_peak", "ruins"],
    lighting: { timeOfDay: 13, mood: "golden", ambient: "#a0988a", outdoorAmbient: "#b8b0a0", sunColor: "#fff2d0", brightness: 2.6, exposure: 0.1, saturation: 0.1, contrast: 0.08, tint: "#fff4e0" },
    fog: { start: 300, end: 2000, color: "#e8d8b8", density: 0.12, haze: 0.9, glare: 0.5 },
    ui: "fantasy",
    uiAccent: "#2f8fbf",
    audio: "western",
    weather: "sandstorm", weatherIntensity: 0.25, clouds: 0.05, walls: "adobe", terrainTint: 0.6,
  },
  {
    id: "winter",
    name: "Winter / Arctic",
    description: "Snowy pines, frozen lakes, igloos and log cabins, blue-white light.",
    group: "nature",
    keywords: ["neige", "snow", "hiver", "winter", "glace", "ice", "arctique", "arctic", "polaire", "polar", "igloo", "noel", "christmas", "ski", "toundra", "tundra"],
    geometry: "chunky_low_poly",
    palette: { primary: "#e8f0f8", secondary: "#8aa0b8", accent: "#ff8040", ground: "#e8eef4", stone: "#8890a0", wood: "#5a4030", foliage: "#3a6a4a", foliageAlt: "#5a8a6a", water: "#5a90c0", roof: "#f0f4f8", wall: "#8a6a48", glow: "#ffe0a0", sky: "#b8d0e8" },
    materials: { ground: "Snow", path: "Snow", roof: "Snow", rock: "Ice" },
    tree: "conifer",
    architecture: { kit: "nordic", roofPitch: 1.2, weathering: 0.4, chimneyChance: 0.9, interiors: true },
    vegetationKit: "arctic",
    vegetationDensity: 0.45,
    propKits: ["arctic", "camp", "village"],
    roadKit: "snow_path",
    biomes: ["snow", "pine_forest", "tundra", "rocky"],
    landmarks: ["mountain_peak", "campfire", "tower", "statue"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 14.5, mood: "overcast", ambient: "#a0b0c8", outdoorAmbient: "#b8c8d8", sunColor: "#f0f8ff", brightness: 2.0, exposure: 0.05, saturation: -0.1, contrast: 0.05, tint: "#eef4ff" },
    fog: { start: 150, end: 1200, color: "#d8e4f0", density: 0.3, haze: 1.2, glare: 0.35 },
    ui: "minimal",
    uiAccent: "#ff8040",
    audio: "chill",
    weather: "snow", weatherIntensity: 0.6, clouds: 0.7, walls: "ice", snowLine: 0.2, terrainTint: 0.5,
  },
  {
    id: "swamp",
    name: "Swamp",
    description: "Murky water, willows, reeds, stilt huts, green fog and fireflies.",
    group: "nature",
    keywords: ["marais", "swamp", "marecage", "bog", "bayou", "mangrove", "tourbiere"],
    geometry: "chunky_low_poly",
    palette: { primary: "#3a5a3a", secondary: "#6a7a5a", accent: "#a0d040", ground: "#3a3a28", stone: "#5a6a58", wood: "#4a3a28", foliage: "#3a6a34", foliageAlt: "#6a8a40", water: "#3a5a48", roof: "#4a4a34", wall: "#7a6a50", mushroom: "#7a9a3a", mushroomAlt: "#9a7a3a", glow: "#c0ff60", sky: "#7a8a80" },
    materials: { ground: "Mud", path: "WoodPlanks", roof: "Grass" },
    tree: "twisted",
    architecture: { kit: "stone_hut", roofPitch: 0.8, weathering: 0.8, chimneyChance: 0.3, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.7,
    propKits: ["docks", "camp", "graveyard"],
    roadKit: "wooden_walkway",
    biomes: ["swamp", "dark_forest", "forest"],
    landmarks: ["giant_tree", "ruins", "well", "statue"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 18, mood: "eerie", ambient: "#5a6a58", outdoorAmbient: "#6a7a68", sunColor: "#c0d0b0", brightness: 1.1, exposure: -0.15, saturation: -0.1, contrast: 0.1, tint: "#e0f0d8" },
    fog: { start: 40, end: 400, color: "#5a6a58", density: 0.6, haze: 2.4, glare: 0.1 },
    mushrooms: 0.25,
    ui: "stylized",
    uiAccent: "#a0d040",
    audio: "ambient_nature",
    weather: "fireflies", weatherIntensity: 0.5, clouds: 0.75, walls: "none", terrainTint: 0.7,
  },
  {
    id: "cartoon",
    name: "Cartoon",
    description: "Saturated candy-like colours, rounded shapes, bright cheerful light.",
    group: "themed",
    keywords: ["cartoon", "toon", "mignon", "cute", "kawaii", "colore", "colorful", "enfant", "kids"],
    geometry: "rounded",
    palette: { primary: "#5ac05a", secondary: "#60b0ff", accent: "#ff7ab0", ground: "#8a6a40", stone: "#b0b0c0", wood: "#a06a40", foliage: "#5ad050", foliageAlt: "#a0f060", water: "#40c0ff", roof: "#ff6060", wall: "#fff0c0", mushroom: "#ff6060", mushroomAlt: "#ffb040", glow: "#ffff80", sky: "#80d0ff" },
    tree: "round",
    architecture: { kit: "timber_frame", roofPitch: 1.1, weathering: 0.1, chimneyChance: 0.8, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.6,
    propKits: ["village", "farm", "playground"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "beach"],
    landmarks: ["windmill", "giant_tree", "well", "statue"],
    lighting: { timeOfDay: 12, mood: "bright", ambient: "#a0a8b8", outdoorAmbient: "#b8c0d0", sunColor: "#ffffff", brightness: 2.5, exposure: 0.15, saturation: 0.35, contrast: 0.1, tint: "#ffffff" },
    fog: { start: 300, end: 1800, color: "#c8e8ff", density: 0.1, haze: 0.3, glare: 0.4 },
    ui: "cartoon",
    uiAccent: "#ff7ab0",
    audio: "cheerful",
    weather: "none", clouds: 0.35, walls: "picket", terrainTint: 0.75,
  },
  {
    id: "horror_gothic",
    name: "Gothic Horror",
    description: "Haunted mansion grounds: dead trees, graveyards, fog, lightning, candle light.",
    group: "themed",
    keywords: ["horreur", "horror", "gothique", "gothic", "manoir", "mansion", "hante", "haunted", "fantome", "ghost", "vampire", "cimetiere", "graveyard", "halloween", "epouvante", "creepy", "scary"],
    geometry: "angular",
    palette: { primary: "#2a2a30", secondary: "#4a4a54", accent: "#c03030", ground: "#2a2824", stone: "#4a4a50", wood: "#3a2a24", foliage: "#2a3a2a", foliageAlt: "#3a4a34", water: "#1a2a30", roof: "#2a2430", wall: "#5a5a60", glow: "#ff9040", sky: "#202030" },
    materials: { wall: "Brick", stoneWall: "Cobblestone", roof: "Slate", path: "Cobblestone", ground: "Mud" },
    tree: "twisted",
    architecture: { kit: "gothic", roofPitch: 1.4, weathering: 0.85, chimneyChance: 0.8, interiors: true, floors: [2, 3] },
    vegetationKit: "dead",
    vegetationDensity: 0.45,
    propKits: ["graveyard", "horror", "ruins"],
    roadKit: "cobblestone_road",
    biomes: ["dark_forest", "swamp", "ruins_field", "meadow"],
    landmarks: ["castle", "tower", "statue", "ruins", "well"],
    settlementType: "abandoned_village",
    lighting: { timeOfDay: 23, mood: "stormy", ambient: "#303040", outdoorAmbient: "#383848", sunColor: "#7080a0", brightness: 0.5, exposure: -0.3, saturation: -0.4, contrast: 0.2, tint: "#c8d0e8" },
    fog: { start: 25, end: 300, color: "#303038", density: 0.7, haze: 3, glare: 0 },
    ui: "horror",
    uiAccent: "#c03030",
    audio: "horror",
    weather: "rain", weatherIntensity: 0.35, clouds: 0.95, walls: "stone_crenellated", terrainTint: 0.7,
  },
  {
    id: "underwater",
    name: "Underwater",
    description: "Ocean-floor world: coral reefs, kelp, sunken ships, blue caustic light.",
    group: "themed",
    keywords: ["sous-marin", "underwater", "ocean", "mer", "sea", "corail", "coral", "atlantide", "atlantis", "sirene", "mermaid", "abysse", "abyss", "aquatique"],
    geometry: "rounded",
    palette: { primary: "#2a6a8a", secondary: "#4a8aa0", accent: "#ff7a50", ground: "#c8b890", stone: "#6a8a90", wood: "#5a4a38", foliage: "#3aa080", foliageAlt: "#ff6080", water: "#1a6090", roof: "#4a9ab0", wall: "#8ab0c0", mushroom: "#ff7a50", mushroomAlt: "#ffc050", glow: "#60ffd0", sky: "#0a3a60" },
    materials: { ground: "Sand", rock: "Slate", wall: "Marble", roof: "Marble" },
    tree: "round",
    architecture: { kit: "greek_temple", roofPitch: 0.4, weathering: 0.7, chimneyChance: 0, interiors: true },
    vegetationKit: "coral",
    vegetationDensity: 0.7,
    propKits: ["underwater", "pirate", "ruins"],
    roadKit: "sand_path",
    biomes: ["ocean_floor", "beach", "rocky"],
    landmarks: ["pirate_ship", "ruins", "statue", "temple", "crystal_spire"],
    settlementType: "outpost",
    lighting: { timeOfDay: 12, mood: "soft", ambient: "#2a5a80", outdoorAmbient: "#3a6a90", sunColor: "#80c0e0", brightness: 1.2, exposure: -0.1, saturation: 0.1, contrast: 0.1, tint: "#a0d0ff" },
    fog: { start: 20, end: 260, color: "#0a4a70", density: 0.7, haze: 3, glare: 0.2 },
    ui: "cartoon",
    uiAccent: "#ff7a50",
    audio: "ambient_nature",
    weather: "bubbles", weatherIntensity: 0.6, clouds: 0, walls: "none", terrainTint: 0.85,
  },
  {
    id: "candy",
    name: "Candy Land",
    description: "Lollipop trees, chocolate rivers, gingerbread houses, pastel skies.",
    group: "themed",
    keywords: ["candy", "bonbon", "sucre", "sugar", "chocolat", "chocolate", "pain d'epice", "gingerbread", "sucette", "lollipop", "gateau", "cake", "pastel"],
    geometry: "rounded",
    palette: { primary: "#ff9ad0", secondary: "#a0e0ff", accent: "#ff4a8a", ground: "#f0d0a0", stone: "#ffd0e0", wood: "#8a4a2a", foliage: "#7ae090", foliageAlt: "#ffb0e0", water: "#8a4a2a", roof: "#ff6a9a", wall: "#c07a4a", mushroom: "#ff6a9a", mushroomAlt: "#ffd050", glow: "#ffffa0", sky: "#ffd0f0" },
    materials: { ground: "Grass", path: "SmoothPlastic", wall: "SmoothPlastic", roof: "SmoothPlastic", rock: "SmoothPlastic", trunk: "SmoothPlastic" },
    tree: "round",
    architecture: { kit: "candy", roofPitch: 1.0, weathering: 0, chimneyChance: 0.7, interiors: true },
    vegetationKit: "candy",
    vegetationDensity: 0.55,
    propKits: ["candy", "playground", "carnival"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "beach"],
    landmarks: ["giant_tree", "windmill", "ferris_wheel", "statue"],
    lighting: { timeOfDay: 12, mood: "bright", ambient: "#c0b0c8", outdoorAmbient: "#d0c8d8", sunColor: "#fff8ff", brightness: 2.6, exposure: 0.15, saturation: 0.4, contrast: 0.05, tint: "#fff4ff" },
    fog: { start: 300, end: 1800, color: "#ffd8f0", density: 0.1, haze: 0.4, glare: 0.5 },
    ui: "candy",
    uiAccent: "#ff4a8a",
    audio: "cheerful",
    weather: "petals", weatherIntensity: 0.4, clouds: 0.3, walls: "picket", terrainTint: 0.95,
  },
  {
    id: "low_poly_minimal",
    name: "Low-Poly Minimal",
    description: "Flat-shaded pastel minimalism: simple blocks, few colours, clean light.",
    group: "themed",
    keywords: ["low poly", "low-poly", "lowpoly", "minimal", "minimaliste", "flat", "simple", "epure", "clean"],
    geometry: "blocky",
    palette: { primary: "#7ab890", secondary: "#c8d0d8", accent: "#f0a040", ground: "#a0c070", stone: "#b0b8c0", wood: "#b08a60", foliage: "#7ac080", foliageAlt: "#a8d890", water: "#70c0e0", roof: "#f07050", wall: "#f4f0e8", glow: "#fff0a0", sky: "#b0d8f8" },
    materials: { trunk: "SmoothPlastic", canopy: "SmoothPlastic", rock: "SmoothPlastic", wall: "SmoothPlastic", stoneWall: "SmoothPlastic", roof: "SmoothPlastic", path: "SmoothPlastic", ground: "Grass", prop: "SmoothPlastic", metal: "SmoothPlastic" },
    tree: "blocky",
    architecture: { kit: "modern_house", roofPitch: 0.8, weathering: 0, chimneyChance: 0.5, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.45,
    propKits: ["village", "suburban", "playground"],
    roadKit: "stone_path",
    biomes: ["meadow", "forest", "beach", "highlands"],
    landmarks: ["windmill", "tower", "statue", "well"],
    lighting: { timeOfDay: 13, mood: "bright", ambient: "#b0b8c0", outdoorAmbient: "#c8d0d8", sunColor: "#ffffff", brightness: 2.4, exposure: 0.1, saturation: 0.1, contrast: 0.02, tint: "#ffffff" },
    fog: { start: 400, end: 2400, color: "#d8e8f8", density: 0.06, haze: 0.2, glare: 0.3 },
    ui: "minimal",
    uiAccent: "#f0a040",
    audio: "chill",
    weather: "none", clouds: 0.3, walls: "none", terrainTint: 0.8,
  },
  {
    id: "voxel",
    name: "Voxel / Blocky",
    description: "Cube-world look: blocky trees, cube hills, pixel-like palette.",
    group: "themed",
    keywords: ["voxel", "cube", "cubique", "blocky", "minecraft", "pixel", "8-bit", "retro blocks"],
    geometry: "blocky",
    palette: { primary: "#5a9a3a", secondary: "#8a8a8a", accent: "#e0a020", ground: "#7a5a3a", stone: "#8a8a8a", wood: "#8a6a3a", foliage: "#4aa030", foliageAlt: "#70c040", water: "#3a70d0", roof: "#8a4a2a", wall: "#d8c8a0", glow: "#ffe060", sky: "#80b8f8" },
    materials: { trunk: "Wood", canopy: "Grass", rock: "Slate", wall: "WoodPlanks", stoneWall: "Cobblestone", roof: "WoodPlanks", path: "Cobblestone", ground: "Grass", prop: "Wood", metal: "Metal" },
    tree: "blocky",
    architecture: { kit: "voxel", roofPitch: 0.9, weathering: 0.1, chimneyChance: 0.5, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.5,
    propKits: ["village", "mine", "farm"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "highlands", "desert", "snow"],
    landmarks: ["tower", "castle", "well", "mountain_peak"],
    lighting: { timeOfDay: 12.5, mood: "bright", ambient: "#a0a8b0", outdoorAmbient: "#b8c0c8", sunColor: "#ffffff", brightness: 2.3, exposure: 0.08, saturation: 0.2, contrast: 0.06, tint: "#ffffff" },
    fog: { start: 300, end: 1600, color: "#c0d8f8", density: 0.12, haze: 0.4, glare: 0.3 },
    ui: "retro",
    uiAccent: "#e0a020",
    audio: "retro",
    weather: "none", clouds: 0.4, walls: "none", terrainTint: 0.75,
  },
];
