import type { StyleFamilyDef } from "./types";

/** Fantasy, historical and nature style families. */
export const STYLE_FAMILIES_A: StyleFamilyDef[] = [
  {
    id: "stylized_mystical",
    name: "Stylized Mystical",
    description: "Chunky low-poly, giant mushrooms, moonlit fog — the WorldForge reference look.",
    group: "fantasy",
    keywords: ["mystique", "mystical", "mysterieux", "brume", "mist", "lune", "moon", "champignon", "mushroom", "feerique"],
    geometry: "chunky_low_poly",
    palette: { primary: "#3e5a45", secondary: "#6d7a8c", accent: "#7b4f8f", ground: "#4a3b2c", stone: "#7c7f86", wood: "#5c3a2a", foliage: "#4a7355", foliageAlt: "#6a9a62", water: "#4d6f86", roof: "#6a5a66", wall: "#9a8b7a", mushroom: "#7b4f8f", mushroomAlt: "#8a3f5f", glow: "#b48cff", sky: "#6d7d9a" },
    tree: "chunky_fantasy",
    architecture: { kit: "medieval_cottage", roofPitch: 0.9, weathering: 0.7, chimneyChance: 0.6, interiors: true },
    vegetationKit: "mushroom",
    vegetationDensity: 0.72,
    propKits: ["village", "forest", "ruins"],
    roadKit: "stone_path",
    biomes: ["dark_forest", "mushroom_grove", "forest", "meadow", "rocky"],
    landmarks: ["giant_tree", "ruins", "portal", "statue"],
    lighting: { timeOfDay: 20.5, mood: "moonlit", ambient: "#5d6b85", outdoorAmbient: "#6b7690", sunColor: "#cfd6e6", brightness: 1.2, exposure: -0.1, saturation: -0.05, contrast: 0.06, tint: "#e2e8ff" },
    fog: { start: 80, end: 640, color: "#7d8aa3", density: 0.36, haze: 1.6, glare: 0.1 },
    mushrooms: 0.35,
    ui: "stylized",
    uiAccent: "#7b4f8f",
    audio: "mystical",
  },
  {
    id: "fantasy",
    name: "High Fantasy",
    description: "Bright enchanted realm: windmills, meadows, colourful roofs, golden light.",
    group: "fantasy",
    keywords: ["fantasy", "fantastique", "magie", "magic", "enchant", "royaume enchante", "fee", "fairy", "elfe", "elf"],
    geometry: "chunky_low_poly",
    palette: { primary: "#4f8a4f", secondary: "#8aa0c0", accent: "#e0b050", ground: "#5a4a30", stone: "#9a9aa0", wood: "#7a4f30", foliage: "#5aa050", foliageAlt: "#8cc060", water: "#4f9fd0", roof: "#b04040", wall: "#e0d0b0", mushroom: "#d05050", mushroomAlt: "#e08040", glow: "#ffe08a", sky: "#8fc0ff" },
    tree: "round",
    architecture: { kit: "timber_frame", roofPitch: 1.0, weathering: 0.3, chimneyChance: 0.7, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.65,
    propKits: ["village", "farm", "forest"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "highlands", "rocky"],
    landmarks: ["windmill", "castle", "giant_tree", "well"],
    lighting: { timeOfDay: 13, mood: "golden", ambient: "#8a90a0", outdoorAmbient: "#a0a8b8", sunColor: "#fff0d0", brightness: 2.2, exposure: 0.05, saturation: 0.15, contrast: 0.05, tint: "#fff5e8" },
    fog: { start: 200, end: 1400, color: "#c0d8f0", density: 0.2, haze: 0.8, glare: 0.3 },
    mushrooms: 0.1,
    ui: "fantasy",
    uiAccent: "#e0b050",
    audio: "orchestral",
  },
  {
    id: "dark_fantasy",
    name: "Dark Fantasy",
    description: "Cursed lands: dead trees, ruins, eerie green glow, thick fog.",
    group: "fantasy",
    keywords: ["dark fantasy", "maudit", "cursed", "sombre", "tenebres", "demon", "necro", "hante", "haunted", "gothique fantasy"],
    geometry: "angular",
    palette: { primary: "#2a2e2a", secondary: "#4a4a58", accent: "#6fbf5f", ground: "#2a2420", stone: "#4c4c54", wood: "#3a2a22", foliage: "#2f3f2a", foliageAlt: "#3f5030", water: "#233038", roof: "#2c2430", wall: "#5a5a60", mushroom: "#5a8f4f", mushroomAlt: "#8a3f5f", glow: "#7fff6f", sky: "#2c3040" },
    tree: "twisted",
    architecture: { kit: "gothic", roofPitch: 1.3, weathering: 0.9, chimneyChance: 0.3, interiors: true },
    vegetationKit: "dead",
    vegetationDensity: 0.5,
    propKits: ["ruins", "graveyard", "horror"],
    roadKit: "dirt_path",
    biomes: ["dark_forest", "swamp", "ruins_field", "rocky"],
    landmarks: ["ruins", "tower", "castle", "statue", "portal"],
    settlementType: "abandoned_village",
    lighting: { timeOfDay: 21, mood: "eerie", ambient: "#3a4040", outdoorAmbient: "#404848", sunColor: "#8fa0a0", brightness: 0.8, exposure: -0.3, saturation: -0.3, contrast: 0.15, tint: "#d0e0d8" },
    fog: { start: 30, end: 320, color: "#3c4840", density: 0.6, haze: 2.5, glare: 0 },
    mushrooms: 0.2,
    ui: "horror",
    uiAccent: "#6fbf5f",
    audio: "horror",
  },
  {
    id: "elven",
    name: "Elven Woodland",
    description: "Graceful curved wooden architecture in giant trees, soft glowing lanterns.",
    group: "fantasy",
    keywords: ["elfe", "elven", "elvish", "sylvain", "woodland realm", "rivendell", "arbre geant"],
    geometry: "smooth_low_poly",
    palette: { primary: "#4a7a5a", secondary: "#c8b890", accent: "#9fd0a0", ground: "#4a4030", stone: "#b0b0a0", wood: "#8a6a48", foliage: "#5a9a5a", foliageAlt: "#a0c070", water: "#5fb0c0", roof: "#6a8a5a", wall: "#e8dcc0", glow: "#c0ffd0", sky: "#a0d0e0" },
    tree: "chunky_fantasy",
    architecture: { kit: "elven", roofPitch: 1.1, weathering: 0.2, chimneyChance: 0.1, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.85,
    propKits: ["forest", "village"],
    roadKit: "stone_path",
    biomes: ["forest", "meadow", "highlands"],
    landmarks: ["giant_tree", "temple", "statue", "well"],
    lighting: { timeOfDay: 16.5, mood: "golden", ambient: "#8a9a8a", outdoorAmbient: "#a0b0a0", sunColor: "#fff5d8", brightness: 1.8, exposure: 0, saturation: 0.1, contrast: 0.04, tint: "#f0fff0" },
    fog: { start: 150, end: 1100, color: "#c0e0d0", density: 0.22, haze: 1.0, glare: 0.3 },
    ui: "fantasy",
    uiAccent: "#9fd0a0",
    audio: "orchestral",
  },
  {
    id: "cartoon",
    name: "Cartoon",
    description: "Saturated candy-like colours, rounded shapes, bright cheerful light.",
    group: "themed",
    keywords: ["cartoon", "toon", "mignon", "cute", "kawaii", "colore", "colorful", "enfant", "kids"],
    geometry: "rounded",
    palette: { primary: "#5ac05a", secondary: "#60b0ff", accent: "#ff7ab0", ground: "#8a6a40", stone: "#b0b0c0", wood: "#a06a40", foliage: "#5ad050", foliageAlt: "#a0f060", water: "#40c0ff", roof: "#ff6060", wall: "#fff0c0", mushroom: "#ff6060", mushroomAlt: "#ffb040", glow: "#ffff80", sky: "#80d0ff" },
    tree: "round",
    architecture: { kit: "timber_frame", roofPitch: 1.1, weathering: 0.1, chimneyChance: 0.8, interiors: true },
    vegetationKit: "temperate",
    vegetationDensity: 0.6,
    propKits: ["village", "farm", "playground"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "beach"],
    landmarks: ["windmill", "giant_tree", "well", "statue"],
    lighting: { timeOfDay: 12, mood: "bright", ambient: "#a0a8b8", outdoorAmbient: "#b8c0d0", sunColor: "#ffffff", brightness: 2.5, exposure: 0.15, saturation: 0.35, contrast: 0.1, tint: "#ffffff" },
    fog: { start: 300, end: 1800, color: "#c8e8ff", density: 0.1, haze: 0.3, glare: 0.4 },
    ui: "cartoon",
    uiAccent: "#ff7ab0",
    audio: "cheerful",
  },
  {
    id: "medieval",
    name: "Medieval",
    description: "Realistic-leaning medieval kingdom: stone keeps, timber houses, cobblestone roads.",
    group: "historical",
    keywords: ["medieval", "moyen age", "chateau", "castle", "chevalier", "knight", "royaume", "kingdom", "donjon", "forteresse"],
    geometry: "angular",
    palette: { primary: "#5a6a4a", secondary: "#8a8a8a", accent: "#b03030", ground: "#5a4a34", stone: "#8a8580", wood: "#6a4a30", foliage: "#4a7a40", foliageAlt: "#6a9a50", water: "#4a7a90", roof: "#6a4a3a", wall: "#c0b090", glow: "#ffc070", sky: "#9ab0c8" },
    tree: "round",
    architecture: { kit: "timber_frame", roofPitch: 1.1, weathering: 0.55, chimneyChance: 0.75, interiors: true, floors: [1, 2] },
    vegetationKit: "temperate",
    vegetationDensity: 0.55,
    propKits: ["village", "farm", "docks"],
    roadKit: "cobblestone_road",
    biomes: ["meadow", "forest", "highlands", "rocky"],
    landmarks: ["castle", "windmill", "tower", "well", "temple"],
    settlementType: "town",
    lighting: { timeOfDay: 15, mood: "soft", ambient: "#8a90a0", outdoorAmbient: "#a0a8b8", sunColor: "#fff0d8", brightness: 1.9, exposure: 0, saturation: 0, contrast: 0.05, tint: "#fff8f0" },
    fog: { start: 200, end: 1500, color: "#b8c8d8", density: 0.2, haze: 0.9, glare: 0.2 },
    ui: "fantasy",
    uiAccent: "#b03030",
    audio: "epic",
  },
  {
    id: "viking",
    name: "Viking / Nordic",
    description: "Longhouses, carved wood, fjords, pine forests and cold light.",
    group: "historical",
    keywords: ["viking", "nordique", "nordic", "norse", "fjord", "valhalla", "longhouse", "scandinav"],
    geometry: "angular",
    palette: { primary: "#3a5a4a", secondary: "#7a8a90", accent: "#c07030", ground: "#4a4a3a", stone: "#707880", wood: "#5a3a28", foliage: "#2f5a3a", foliageAlt: "#4a7a4a", water: "#3a6a80", roof: "#4a5a3a", wall: "#6a4a34", glow: "#ffb060", sky: "#8aa0b8" },
    tree: "conifer",
    architecture: { kit: "nordic", roofPitch: 1.2, weathering: 0.6, chimneyChance: 0.5, interiors: true },
    vegetationKit: "conifer",
    vegetationDensity: 0.6,
    propKits: ["village", "docks", "camp"],
    roadKit: "dirt_path",
    biomes: ["pine_forest", "highlands", "snow", "rocky", "beach"],
    landmarks: ["statue", "temple", "tower", "campfire"],
    lighting: { timeOfDay: 16, mood: "overcast", ambient: "#7a8898", outdoorAmbient: "#8a98a8", sunColor: "#e8f0ff", brightness: 1.5, exposure: -0.05, saturation: -0.1, contrast: 0.08, tint: "#e8f0ff" },
    fog: { start: 120, end: 900, color: "#a8b8c8", density: 0.35, haze: 1.4, glare: 0.1 },
    ui: "fantasy",
    uiAccent: "#c07030",
    audio: "epic",
  },
  {
    id: "ancient_egypt",
    name: "Ancient Egypt",
    description: "Sandstone temples, obelisks, pyramids, palm oases along a river.",
    group: "historical",
    keywords: ["egypte", "egypt", "pharaon", "pharaoh", "pyramide", "pyramid", "sphinx", "nil", "nile", "obelisque"],
    geometry: "angular",
    palette: { primary: "#c8a860", secondary: "#8a7050", accent: "#2f8fbf", ground: "#c8a868", stone: "#d8c090", wood: "#8a6a40", foliage: "#5a8a3a", foliageAlt: "#7aa050", water: "#3a8ab0", roof: "#d0b078", wall: "#e0c890", glow: "#ffd070", sky: "#a8d0f0" },
    materials: { wall: "Sandstone", stoneWall: "Sandstone", roof: "Sandstone", path: "Sandstone", ground: "Sand", rock: "Sandstone" },
    tree: "round",
    architecture: { kit: "egyptian", roofPitch: 0.3, weathering: 0.4, chimneyChance: 0, interiors: true },
    vegetationKit: "desert",
    vegetationDensity: 0.25,
    propKits: ["egypt", "camp", "docks"],
    roadKit: "sand_path",
    biomes: ["desert", "beach", "rocky"],
    landmarks: ["temple", "statue", "mountain_peak", "well"],
    lighting: { timeOfDay: 13, mood: "golden", ambient: "#a0988a", outdoorAmbient: "#b8b0a0", sunColor: "#fff2d0", brightness: 2.6, exposure: 0.1, saturation: 0.1, contrast: 0.08, tint: "#fff4e0" },
    fog: { start: 300, end: 2000, color: "#e8d8b8", density: 0.12, haze: 0.9, glare: 0.5 },
    ui: "fantasy",
    uiAccent: "#2f8fbf",
    audio: "orchestral",
  },
  {
    id: "ancient_greece",
    name: "Ancient Greece / Rome",
    description: "White marble temples, columns, olive groves, terracotta roofs by the sea.",
    group: "historical",
    keywords: ["grece", "greece", "greek", "rome", "roman", "romain", "antique", "olympe", "olympus", "colisee", "colosseum", "marbre", "marble"],
    geometry: "angular",
    palette: { primary: "#7a9a6a", secondary: "#e8e4dc", accent: "#c05030", ground: "#a08a60", stone: "#e8e4dc", wood: "#8a6a48", foliage: "#5a8a4a", foliageAlt: "#8ab060", water: "#2f8fc0", roof: "#c06040", wall: "#f0ece0", glow: "#ffe0a0", sky: "#a0d0ff" },
    materials: { wall: "Marble", stoneWall: "Marble", roof: "Slate", path: "Sandstone", rock: "Limestone" },
    tree: "round",
    architecture: { kit: "greek_temple", roofPitch: 0.5, weathering: 0.35, chimneyChance: 0, interiors: true },
    vegetationKit: "savanna",
    vegetationDensity: 0.4,
    propKits: ["greek", "docks", "farm"],
    roadKit: "stone_path",
    biomes: ["meadow", "beach", "rocky", "highlands"],
    landmarks: ["temple", "statue", "well", "tower"],
    lighting: { timeOfDay: 14, mood: "bright", ambient: "#a0a8b0", outdoorAmbient: "#b8c0c8", sunColor: "#fff8e8", brightness: 2.4, exposure: 0.08, saturation: 0.08, contrast: 0.06, tint: "#fffaf0" },
    fog: { start: 300, end: 2000, color: "#d0e4f8", density: 0.12, haze: 0.6, glare: 0.4 },
    ui: "fantasy",
    uiAccent: "#c05030",
    audio: "orchestral",
  },
  {
    id: "feudal_japan",
    name: "Feudal Japan",
    description: "Pagoda roofs, torii gates, cherry blossoms, stone lanterns, bamboo.",
    group: "historical",
    keywords: ["japon", "japan", "japonais", "japanese", "samourai", "samurai", "ninja", "shinobi", "torii", "pagode", "pagoda", "cerisier", "sakura", "edo", "kyoto"],
    geometry: "angular",
    palette: { primary: "#6a8a5a", secondary: "#e8dcc8", accent: "#c03030", ground: "#6a5a40", stone: "#8a8a88", wood: "#5a3a28", foliage: "#4a8a4a", foliageAlt: "#f0a0c0", water: "#4a90b0", roof: "#3a3a48", wall: "#f0e8d8", glow: "#ffd090", sky: "#b8d8f0" },
    tree: "round",
    architecture: { kit: "japanese", roofPitch: 0.6, weathering: 0.3, chimneyChance: 0, interiors: true, floors: [1, 2] },
    vegetationKit: "cherry",
    vegetationDensity: 0.6,
    propKits: ["japanese", "village", "farm"],
    roadKit: "stone_path",
    biomes: ["forest", "meadow", "highlands", "rocky"],
    landmarks: ["temple", "statue", "mountain_peak", "well"],
    lighting: { timeOfDay: 15.5, mood: "soft", ambient: "#9098a8", outdoorAmbient: "#a8b0c0", sunColor: "#fff4e4", brightness: 2.0, exposure: 0.02, saturation: 0.08, contrast: 0.05, tint: "#fff6f0" },
    fog: { start: 150, end: 1200, color: "#d0d8e8", density: 0.25, haze: 1.1, glare: 0.2 },
    ui: "fantasy",
    uiAccent: "#c03030",
    audio: "orchestral",
  },
  {
    id: "wild_west",
    name: "Wild West",
    description: "Wooden false-front saloons, dusty streets, cacti, water towers, red mesas.",
    group: "historical",
    keywords: ["western", "wild west", "far west", "cowboy", "saloon", "sherif", "sheriff", "desert town", "mesa", "ranch"],
    geometry: "angular",
    palette: { primary: "#b08050", secondary: "#c8a070", accent: "#a03020", ground: "#b8905a", stone: "#b8785a", wood: "#8a5a34", foliage: "#7a8a40", foliageAlt: "#9aa050", water: "#6a9aa0", roof: "#6a4a30", wall: "#a07850", glow: "#ffc060", sky: "#c0d8f0" },
    materials: { ground: "Sand", path: "Ground", rock: "Sandstone" },
    tree: "blocky",
    architecture: { kit: "western_facade", roofPitch: 0.4, weathering: 0.7, chimneyChance: 0.3, interiors: true, floors: [1, 2] },
    vegetationKit: "desert",
    vegetationDensity: 0.25,
    propKits: ["western", "farm", "camp"],
    roadKit: "dirt_path",
    biomes: ["desert", "rocky", "meadow"],
    landmarks: ["mountain_peak", "well", "tower", "campfire"],
    settlementType: "town",
    lighting: { timeOfDay: 17, mood: "golden", ambient: "#a0907a", outdoorAmbient: "#b8a890", sunColor: "#ffd8a0", brightness: 2.3, exposure: 0.05, saturation: 0.05, contrast: 0.1, tint: "#ffe8d0" },
    fog: { start: 250, end: 1800, color: "#e0c8a8", density: 0.15, haze: 1.2, glare: 0.5 },
    ui: "retro",
    uiAccent: "#a03020",
    audio: "western",
  },
  {
    id: "pirate",
    name: "Pirate Cove",
    description: "Tropical harbour town, docks, shipwrecks, cannons, palm trees and lagoons.",
    group: "historical",
    keywords: ["pirate", "corsaire", "tresor", "treasure", "galion", "galleon", "caraibes", "caribbean", "port", "harbor", "harbour", "crique", "cove"],
    geometry: "chunky_low_poly",
    palette: { primary: "#4a8a6a", secondary: "#c8b890", accent: "#c0302a", ground: "#c8b080", stone: "#8a8078", wood: "#6a4a30", foliage: "#3a9a5a", foliageAlt: "#7ac060", water: "#2fb0c0", roof: "#5a3a28", wall: "#a08a68", glow: "#ffc070", sky: "#80c8f0" },
    materials: { ground: "Sand", path: "WoodPlanks" },
    tree: "round",
    architecture: { kit: "shack", roofPitch: 0.8, weathering: 0.75, chimneyChance: 0.3, interiors: true },
    vegetationKit: "tropical",
    vegetationDensity: 0.55,
    propKits: ["pirate", "docks", "camp"],
    roadKit: "wooden_walkway",
    biomes: ["beach", "forest", "rocky"],
    landmarks: ["tower", "ruins", "campfire", "statue"],
    settlementType: "harbor",
    lighting: { timeOfDay: 16.5, mood: "golden", ambient: "#9aa0a8", outdoorAmbient: "#b0b8c0", sunColor: "#ffe8c0", brightness: 2.2, exposure: 0.05, saturation: 0.15, contrast: 0.08, tint: "#fff0e0" },
    fog: { start: 200, end: 1600, color: "#c8e0f0", density: 0.18, haze: 0.9, glare: 0.4 },
    ui: "fantasy",
    uiAccent: "#c0302a",
    audio: "tropical",
  },
  {
    id: "steampunk",
    name: "Victorian Steampunk",
    description: "Brick and brass, gears, pipes, gas lamps, smog and airships.",
    group: "historical",
    keywords: ["steampunk", "victorien", "victorian", "vapeur", "steam", "engrenage", "gear", "laiton", "brass", "londres", "london"],
    geometry: "angular",
    palette: { primary: "#6a5a48", secondary: "#8a7a68", accent: "#c8963a", ground: "#5a5048", stone: "#7a7068", wood: "#4a3a2a", foliage: "#4a6a3a", foliageAlt: "#6a8a4a", water: "#4a5a60", roof: "#3a3a40", wall: "#8a5a48", glow: "#ffb050", sky: "#8a8a90" },
    materials: { wall: "Brick", stoneWall: "Brick", roof: "Metal", path: "Cobblestone", metal: "CorrodedMetal" },
    tree: "round",
    architecture: { kit: "victorian", roofPitch: 1.2, weathering: 0.6, chimneyChance: 0.95, interiors: true, floors: [2, 3] },
    vegetationKit: "temperate",
    vegetationDensity: 0.3,
    propKits: ["industrial", "urban", "village"],
    roadKit: "brick_road",
    biomes: ["meadow", "rocky", "highlands"],
    landmarks: ["tower", "statue", "windmill", "well"],
    settlementType: "town",
    lighting: { timeOfDay: 17.5, mood: "overcast", ambient: "#7a7068", outdoorAmbient: "#908878", sunColor: "#f0d8b0", brightness: 1.5, exposure: -0.05, saturation: -0.15, contrast: 0.12, tint: "#f0e4d0" },
    fog: { start: 60, end: 700, color: "#9a9088", density: 0.45, haze: 2.2, glare: 0.2 },
    ui: "retro",
    uiAccent: "#c8963a",
    audio: "industrial",
  },
  {
    id: "realistic",
    name: "Realistic Nature",
    description: "Natural palette, realistic proportions, subtle light — forests, lakes, mountains.",
    group: "nature",
    keywords: ["realiste", "realistic", "realism", "nature", "naturel", "photoreal", "montagne", "mountain", "lac", "lake", "randonnee"],
    geometry: "smooth_low_poly",
    palette: { primary: "#4a6a3a", secondary: "#7a7a78", accent: "#c08040", ground: "#5a4a34", stone: "#7a7874", wood: "#5a4030", foliage: "#3f6a34", foliageAlt: "#6a8a40", water: "#3a6a80", roof: "#5a4a40", wall: "#b0a088", glow: "#ffe0b0", sky: "#8ab8e0" },
    tree: "conifer",
    architecture: { kit: "modern_house", roofPitch: 0.7, weathering: 0.3, chimneyChance: 0.5, interiors: true },
    vegetationKit: "conifer",
    vegetationDensity: 0.7,
    propKits: ["camp", "forest", "farm"],
    roadKit: "dirt_path",
    biomes: ["pine_forest", "forest", "meadow", "highlands", "rocky"],
    landmarks: ["mountain_peak", "campfire", "tower", "well"],
    settlementType: "hamlet",
    lighting: { timeOfDay: 15, mood: "soft", ambient: "#8890a0", outdoorAmbient: "#a0a8b8", sunColor: "#fff4e4", brightness: 2.0, exposure: 0, saturation: -0.05, contrast: 0.06, tint: "#fbf8f4" },
    fog: { start: 250, end: 2000, color: "#c0d0e0", density: 0.18, haze: 0.8, glare: 0.25 },
    ui: "minimal",
    uiAccent: "#c08040",
    audio: "ambient_nature",
  },
];
