/**
 * UI strings of a generated game, per language. The libraries decide how a screen looks; this table
 * decides what it says. `packages/roblox-export` ships it into `src/ui/strings.generated.ts`, the
 * screens read `L.<key>`, and `GameConfig.ui.locale` picks the column — so a French prompt produces a
 * French game. A missing key falls back to English (the test forbids that in practice).
 */
export const UI_LOCALES = ["en", "fr", "es", "pt", "de"] as const;
export type UiLocale = (typeof UI_LOCALES)[number];

/** English is the reference: every other locale must cover exactly these keys. */
export const UI_STRINGS_EN = {
  // window titles + HUD buttons
  shop: "Shop",
  inventory: "Inventory",
  backpack: "Backpack",
  quests: "Quests",
  crafting: "Crafting",
  craft: "Craft",
  leaderboard: "Leaderboard",
  ranking: "Ranking",
  teams: "Teams",
  settings: "Settings",
  menu: "Menu",
  resume: "Resume",
  map: "MAP",
  mapLoading: "MAP — loading",
  hunger: "HUNGER",
  // sections
  resources: "Resources",
  consumables: "Consumables",
  upgrades: "Upgrades",
  activeBuffs: "Active buffs",
  inProgress: "In progress",
  completed: "Completed",
  audio: "Audio",
  display: "Display",
  all: "All",
  items: "Items",
  robux: "Robux",
  // shop
  buy: "Buy",
  owned: "Owned",
  claimed: "Claimed",
  confirmPurchase: "Confirm purchase",
  /** {item} and {price} are replaced */
  confirmBuy: "Buy {item} for {price} {currency}?",
  cancel: "Cancel",
  /** {count} */
  youHave: "You have: {count}",
  /** {minutes} */
  minutesLeft: "{minutes}m left",
  gamePass: "GAME PASS",
  // inventory / crafting
  search: "Search…",
  emptyBackpack: "Nothing yet — gather, farm or mine to fill the backpack.",
  noRecipe: "No recipe yet — add them to design/game.spec.json (crafting.recipes).",
  noQuest: "No quest in this game yet — add them to design/game.spec.json.",
  consumable: "Consumable",
  resource: "Resource",
  /** {time} */
  timeLeft: "{time} left",
  // leaderboard / teams / rounds
  /** {stat} */
  rankedBy: "Ranked by {stat}",
  waitingPlayers: "Waiting for players…",
  soloMode: "This mode is solo — see the leaderboard for the ranking.",
  /** {phase} */
  phase: "Phase: {phase}",
  score: "Score",
  // settings
  music: "Music",
  soundEffects: "Sound effects",
  cameraShake: "Camera shake",
  minimap: "Minimap",
  uiScale: "UI scale",
  settingsSaved: "Settings are saved with your profile and restored when you rejoin.",
  on: "ON",
  off: "OFF",
  // loading
  shapingWorld: "Shaping the world…",
  // rarity
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  epic: "Epic",
  legendary: "Legendary",
};

export type UiStringKey = keyof typeof UI_STRINGS_EN;
export type UiStringTable = Record<UiStringKey, string>;

const fr: UiStringTable = {
  shop: "Boutique",
  inventory: "Inventaire",
  backpack: "Sac",
  quests: "Quêtes",
  crafting: "Artisanat",
  craft: "Fabriquer",
  leaderboard: "Classement",
  ranking: "Classement",
  teams: "Équipes",
  settings: "Réglages",
  menu: "Menu",
  resume: "Reprendre",
  map: "CARTE",
  mapLoading: "CARTE — chargement",
  hunger: "FAIM",
  resources: "Ressources",
  consumables: "Consommables",
  upgrades: "Améliorations",
  activeBuffs: "Bonus actifs",
  inProgress: "En cours",
  completed: "Terminées",
  audio: "Audio",
  display: "Affichage",
  all: "Tout",
  items: "Objets",
  robux: "Robux",
  buy: "Acheter",
  owned: "Obtenu",
  claimed: "Récupéré",
  confirmPurchase: "Confirmer l'achat",
  confirmBuy: "Acheter {item} pour {price} {currency} ?",
  cancel: "Annuler",
  youHave: "Vous en avez : {count}",
  minutesLeft: "{minutes} min restantes",
  gamePass: "PASS",
  search: "Rechercher…",
  emptyBackpack: "Rien pour l'instant — récoltez, cultivez ou minez pour remplir le sac.",
  noRecipe: "Aucune recette — ajoutez-les dans design/game.spec.json (crafting.recipes).",
  noQuest: "Aucune quête dans ce jeu — ajoutez-les dans design/game.spec.json.",
  consumable: "Consommable",
  resource: "Ressource",
  timeLeft: "{time} restant",
  rankedBy: "Classé par {stat}",
  waitingPlayers: "En attente de joueurs…",
  soloMode: "Ce mode est solo — voyez le classement pour le palmarès.",
  phase: "Phase : {phase}",
  score: "Score",
  music: "Musique",
  soundEffects: "Effets sonores",
  cameraShake: "Secousse caméra",
  minimap: "Minicarte",
  uiScale: "Taille de l'interface",
  settingsSaved: "Les réglages sont enregistrés avec votre profil et restaurés à la reconnexion.",
  on: "OUI",
  off: "NON",
  shapingWorld: "Création du monde…",
  common: "Commun",
  uncommon: "Peu commun",
  rare: "Rare",
  epic: "Épique",
  legendary: "Légendaire",
};

const es: UiStringTable = {
  shop: "Tienda",
  inventory: "Inventario",
  backpack: "Mochila",
  quests: "Misiones",
  crafting: "Fabricación",
  craft: "Fabricar",
  leaderboard: "Clasificación",
  ranking: "Clasificación",
  teams: "Equipos",
  settings: "Ajustes",
  menu: "Menú",
  resume: "Continuar",
  map: "MAPA",
  mapLoading: "MAPA — cargando",
  hunger: "HAMBRE",
  resources: "Recursos",
  consumables: "Consumibles",
  upgrades: "Mejoras",
  activeBuffs: "Mejoras activas",
  inProgress: "En curso",
  completed: "Completadas",
  audio: "Audio",
  display: "Pantalla",
  all: "Todo",
  items: "Objetos",
  robux: "Robux",
  buy: "Comprar",
  owned: "Obtenido",
  claimed: "Reclamado",
  confirmPurchase: "Confirmar compra",
  confirmBuy: "¿Comprar {item} por {price} {currency}?",
  cancel: "Cancelar",
  youHave: "Tienes: {count}",
  minutesLeft: "{minutes} min restantes",
  gamePass: "PASE",
  search: "Buscar…",
  emptyBackpack: "Nada aún — recoge, cultiva o mina para llenar la mochila.",
  noRecipe: "Sin recetas — añádelas en design/game.spec.json (crafting.recipes).",
  noQuest: "Sin misiones — añádelas en design/game.spec.json.",
  consumable: "Consumible",
  resource: "Recurso",
  timeLeft: "quedan {time}",
  rankedBy: "Ordenado por {stat}",
  waitingPlayers: "Esperando jugadores…",
  soloMode: "Este modo es individual — mira la clasificación.",
  phase: "Fase: {phase}",
  score: "Puntos",
  music: "Música",
  soundEffects: "Efectos de sonido",
  cameraShake: "Vibración de cámara",
  minimap: "Minimapa",
  uiScale: "Tamaño de la interfaz",
  settingsSaved: "Los ajustes se guardan con tu perfil y se restauran al volver.",
  on: "SÍ",
  off: "NO",
  shapingWorld: "Creando el mundo…",
  common: "Común",
  uncommon: "Poco común",
  rare: "Raro",
  epic: "Épico",
  legendary: "Legendario",
};

const pt: UiStringTable = {
  shop: "Loja",
  inventory: "Inventário",
  backpack: "Mochila",
  quests: "Missões",
  crafting: "Criação",
  craft: "Criar",
  leaderboard: "Classificação",
  ranking: "Ranking",
  teams: "Equipes",
  settings: "Configurações",
  menu: "Menu",
  resume: "Continuar",
  map: "MAPA",
  mapLoading: "MAPA — carregando",
  hunger: "FOME",
  resources: "Recursos",
  consumables: "Consumíveis",
  upgrades: "Melhorias",
  activeBuffs: "Bônus ativos",
  inProgress: "Em andamento",
  completed: "Concluídas",
  audio: "Áudio",
  display: "Tela",
  all: "Tudo",
  items: "Itens",
  robux: "Robux",
  buy: "Comprar",
  owned: "Adquirido",
  claimed: "Resgatado",
  confirmPurchase: "Confirmar compra",
  confirmBuy: "Comprar {item} por {price} {currency}?",
  cancel: "Cancelar",
  youHave: "Você tem: {count}",
  minutesLeft: "{minutes} min restantes",
  gamePass: "PASSE",
  search: "Pesquisar…",
  emptyBackpack: "Nada ainda — colete, plante ou minere para encher a mochila.",
  noRecipe: "Sem receitas — adicione em design/game.spec.json (crafting.recipes).",
  noQuest: "Sem missões — adicione em design/game.spec.json.",
  consumable: "Consumível",
  resource: "Recurso",
  timeLeft: "resta {time}",
  rankedBy: "Ordenado por {stat}",
  waitingPlayers: "Aguardando jogadores…",
  soloMode: "Este modo é solo — veja a classificação.",
  phase: "Fase: {phase}",
  score: "Pontos",
  music: "Música",
  soundEffects: "Efeitos sonoros",
  cameraShake: "Tremor de câmera",
  minimap: "Minimapa",
  uiScale: "Tamanho da interface",
  settingsSaved: "As configurações ficam salvas no seu perfil e voltam quando você entrar de novo.",
  on: "SIM",
  off: "NÃO",
  shapingWorld: "Criando o mundo…",
  common: "Comum",
  uncommon: "Incomum",
  rare: "Raro",
  epic: "Épico",
  legendary: "Lendário",
};

const de: UiStringTable = {
  shop: "Shop",
  inventory: "Inventar",
  backpack: "Rucksack",
  quests: "Quests",
  crafting: "Handwerk",
  craft: "Herstellen",
  leaderboard: "Rangliste",
  ranking: "Rangliste",
  teams: "Teams",
  settings: "Einstellungen",
  menu: "Menü",
  resume: "Weiter",
  map: "KARTE",
  mapLoading: "KARTE — lädt",
  hunger: "HUNGER",
  resources: "Rohstoffe",
  consumables: "Verbrauch",
  upgrades: "Upgrades",
  activeBuffs: "Aktive Boni",
  inProgress: "Laufend",
  completed: "Erledigt",
  audio: "Audio",
  display: "Anzeige",
  all: "Alle",
  items: "Gegenstände",
  robux: "Robux",
  buy: "Kaufen",
  owned: "Im Besitz",
  claimed: "Abgeholt",
  confirmPurchase: "Kauf bestätigen",
  confirmBuy: "{item} für {price} {currency} kaufen?",
  cancel: "Abbrechen",
  youHave: "Du hast: {count}",
  minutesLeft: "{minutes} Min. übrig",
  gamePass: "GAME PASS",
  search: "Suchen…",
  emptyBackpack: "Noch nichts — sammle, farme oder grabe, um den Rucksack zu füllen.",
  noRecipe: "Keine Rezepte — füge sie in design/game.spec.json hinzu (crafting.recipes).",
  noQuest: "Noch keine Quests — füge sie in design/game.spec.json hinzu.",
  consumable: "Verbrauchsgut",
  resource: "Rohstoff",
  timeLeft: "{time} übrig",
  rankedBy: "Sortiert nach {stat}",
  waitingPlayers: "Warte auf Spieler…",
  soloMode: "Dieser Modus ist Solo — siehe die Rangliste.",
  phase: "Phase: {phase}",
  score: "Punkte",
  music: "Musik",
  soundEffects: "Soundeffekte",
  cameraShake: "Kamerawackeln",
  minimap: "Minikarte",
  uiScale: "UI-Größe",
  settingsSaved: "Einstellungen werden im Profil gespeichert und beim nächsten Besuch geladen.",
  on: "AN",
  off: "AUS",
  shapingWorld: "Welt wird erschaffen…",
  common: "Gewöhnlich",
  uncommon: "Selten",
  rare: "Rar",
  epic: "Episch",
  legendary: "Legendär",
};

export const UI_STRINGS: Record<UiLocale, UiStringTable> = { en: UI_STRINGS_EN, fr, es, pt, de };

/** Words that only appear in one of the supported languages (accents alone are ambiguous). */
const LOCALE_HINTS: Record<UiLocale, string[]> = {
  en: [],
  fr: [" un ", " une ", " des ", " avec ", " dans ", " jeu ", " monde ", " joueur ", " boutique ", " ville ", " château", " forêt", " je veux ", " sur une ", " qui ", " pour "],
  es: [" un juego ", " mundo ", " con ", " jugador ", " tienda ", " ciudad ", " bosque ", " quiero ", " sobre ", " para "],
  pt: [" um jogo ", " mundo ", " com ", " jogador ", " loja ", " cidade ", " floresta ", " quero ", " sobre ", " para "],
  de: [" ein spiel ", " welt ", " mit ", " spieler ", " laden ", " stadt ", " wald ", " ich will ", " auf einer "],
};

/**
 * Guesses the language of a prompt so the generated game speaks it. English is the default and wins
 * ties, because a prompt with a couple of borrowed words is usually English.
 */
export function detectLocale(prompt: string): UiLocale {
  const t = ` ${prompt.toLowerCase()} `;
  let best: UiLocale = "en";
  let score = 0;
  for (const locale of UI_LOCALES) {
    if (locale === "en") continue;
    let hits = 0;
    for (const hint of LOCALE_HINTS[locale]) if (t.includes(hint)) hits += 1;
    if (hits > score) {
      score = hits;
      best = locale;
    }
  }
  return score >= 2 ? best : "en";
}

/** Replaces `{name}` placeholders. */
export function formatString(template: string, values: Record<string, string | number>): string {
  let out = template;
  for (const [key, value] of Object.entries(values)) out = out.split(`{${key}}`).join(`${value}`);
  return out;
}
