import type { StyleBible } from "@worldforge/core";
import { generateTexture, textureSetForStyle, type TextureMaps, type TextureSpec } from "./generate";
import { encodePng, type Deflate } from "./png";

/**
 * `design/textures.manifest.json` — the texture set of a project: which PNGs exist under
 * assets/textures/, which Roblox base material each overrides, tiling, and the asset ids once the
 * images are uploaded (0 until then). The runtime (`src/world/Materials.ts`) builds MaterialVariants
 * from the ids; the viewer uses the PNGs directly.
 */
export interface TextureManifestEntry {
  id: string;
  kind: TextureSpec["kind"];
  baseMaterial: TextureSpec["baseMaterial"];
  studsPerTile: number;
  files: { color: string; normal: string; roughness: string };
  assetIds: { color: number; normal: number; roughness: number };
}

export interface TextureManifest {
  version: 1;
  style: string;
  seed: number;
  size: number;
  entries: TextureManifestEntry[];
}

export interface GeneratedTextureFile {
  path: string;
  bytes: Uint8Array;
}

export interface GenerateTexturesOptions {
  size?: number;
  deflate?: Deflate;
  onProgress?: (done: number, total: number, id: string) => void;
  /** Keep the raw maps (previews) in the result. */
  keepMaps?: boolean;
}

export interface GenerateTexturesResult {
  manifest: TextureManifest;
  files: GeneratedTextureFile[];
  maps: TextureMaps[];
}

/** Generate every texture of the style's set as PNG files + manifest (pure; the caller writes the files). */
export async function generateTextureSet(style: StyleBible, seed: number, opts: GenerateTexturesOptions = {}): Promise<GenerateTexturesResult> {
  const size = opts.size ?? 512;
  const specs = textureSetForStyle(style);
  const files: GeneratedTextureFile[] = [];
  const maps: TextureMaps[] = [];
  const entries: TextureManifestEntry[] = [];
  let done = 0;
  for (const spec of specs) {
    const m = generateTexture(spec, seed + hashId(spec.id), size);
    const dir = `assets/textures/${style.id}`;
    const filesFor = { color: `${dir}/${spec.id}_color.png`, normal: `${dir}/${spec.id}_normal.png`, roughness: `${dir}/${spec.id}_roughness.png` };
    files.push({ path: filesFor.color, bytes: await encodePng(size, size, m.color, 3, opts.deflate) });
    files.push({ path: filesFor.normal, bytes: await encodePng(size, size, m.normal, 3, opts.deflate) });
    files.push({ path: filesFor.roughness, bytes: await encodePng(size, size, m.roughness, 3, opts.deflate) });
    entries.push({ id: spec.id, kind: spec.kind, baseMaterial: spec.baseMaterial, studsPerTile: spec.studsPerTile, files: filesFor, assetIds: { color: 0, normal: 0, roughness: 0 } });
    if (opts.keepMaps) maps.push(m);
    done++;
    opts.onProgress?.(done, specs.length, spec.id);
  }
  return { manifest: { version: 1, style: style.id, seed, size, entries }, files, maps };
}

function hashId(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}

/** Merge uploaded asset ids into an existing manifest (keeps files / order). */
export function withAssetIds(manifest: TextureManifest, ids: Record<string, Partial<TextureManifestEntry["assetIds"]>>): TextureManifest {
  return { ...manifest, entries: manifest.entries.map((e) => ({ ...e, assetIds: { ...e.assetIds, ...(ids[e.id] ?? {}) } })) };
}

/** `src/shared/textures.ts` for the roblox-ts template: the MaterialVariant table the runtime applies. */
export function buildTexturesTs(manifest: TextureManifest | null): string {
  const entries = manifest?.entries ?? [];
  const lines = entries.map((e) => `\t{ id: ${JSON.stringify(e.id)}, baseMaterial: ${JSON.stringify(e.baseMaterial)}, studsPerTile: ${e.studsPerTile}, color: ${e.assetIds.color}, normal: ${e.assetIds.normal}, roughness: ${e.assetIds.roughness} },`);
  return `// Generated by WorldForge from design/textures.manifest.json — do not edit (regenerate the textures instead).
export interface TextureEntry {
\tid: string;
\tbaseMaterial: string;
\tstudsPerTile: number;
\t/** Roblox image asset ids (0 = not uploaded yet → the base material stays as-is). */
\tcolor: number;
\tnormal: number;
\troughness: number;
}

export const TextureSet: TextureEntry[] = [
${lines.join("\n")}
];
`;
}
